- package.json
- packages/@dcl/dcl-rollup/ecs.config.ts
- packages/decentraland-ecs/.gitignore
- packages/decentraland-ecs/package.json
- packages/decentraland-ecs/src/setupProxy.js
- test/decentraland-ecs/setup-proxy.spec.ts
Add the setupProxy.js to the package and fix the context that rollup build.
The setupProxy.js is a proxy loaded by the CLI which allows mapping different endpoints.
See more https://github.com/decentraland/sdk/issues/12
https://github.com/decentraland/cli/pull/569
> feat: include the new setupProxy.js

- packages/decentraland-ecs/src/setupExport.ts
- test/decentraland-ecs/setup-export.spec.ts
Add the setupExport function adapted to new package @dcl/kernel and @dcl/unity-renderer. It creates the export directory with the project files and dependencies.
In accordance with the new responsibility to this package to export the project and serve the dependencies.
1. Clone this repository and checkout this branch
2. Install dependencies with `make install`
3. Build with `make build`
4. Link decentraland-ecs and @dcl/build-ecs with `cd packages/decentraland-ecs && npm link && cd ../@dcl/build-ecs && npm link`
5. Go to project folder and run `npm install @dcl/kernel@next && npm link decentraland-ecs @dcl/build-ecs`
6. Run `dcl export`
> feat: add setupExport function

- .github/workflows/ci.yml
- Makefile
- packages/decentraland-ecs/package.json
- scripts/helpers.ts
- scripts/prepare-local-ecs.spec.ts
- test/decentraland-ecs/local-build-test.spec.ts
Add a CI job and script which pack the decentraland-ecs package with local dependencies. 
To make the PR tests easier, you can download artifacts and install them with one command.
1. Go to 'Checks' tab and download the artifact **'local-decentraland-ecs.zip'** in your scene directory
2. Run `tar -xvf local-decentraland-ecs.zip && tar -xvf local-decentraland-ecs.tgz` to uncompress the artifact
3. Run `npm install ./package`
4. Test with `dcl start` if your CLI version is 3.7.0 or lower. Otherwise you can test with `dcl start --skip-version-checks`
> chore: add a local decentraland-ecs built artifacts

- packages/decentraland-ecs/src/setupProxy.ts
Replace folder string inverted slash to slash 
path.resolve in windows returns inverted slash. This breaks the path processing
> fix: crop work directory to works in window

- packages/decentraland-ecs/src/setupExport.ts
Add the images copy from kernel packages (decentraland-connect) to export directory.
This folder has already serve through setupProxy.ts in preview.
To get working the export spinner.
> feat: add to copy images in setup export

- packages/decentraland-ecs/package.json
- packages/decentraland-ecs/src/setupExport.ts
- packages/decentraland-ecs/src/setupUtils.ts
Now it reads the .dclignore file to exclude the paths specified there from `dcl export` and `dcl start`.
Also, it changes the base64 hash to sha1 in export to no expose the path where the export is done.
As of the preview and export were added, the .dclignore hasn't been considered to this jobs, so the export can be recursively self-added and in the same way preview include export dir. This causes that the export directory non stop increasement
> fix: recursive export, now it ignores the files specified in .dclignore

- packages/decentraland-ecs/src/decentraland/Components.ts
Restore the old PictureFrameStyle enum
To ensure compatibility old scene which were made with the old enum.
https://github.com/decentraland/sdk/issues/52
See previous enum in https://github.com/decentraland/explorer/blob/master/kernel/packages/decentraland-ecs/src/decentraland/Components.ts#L383
> fix: revert PictureFrameStyle enum to lowercase original one

- packages/decentraland-ecs/src/setupExport.ts
- scripts/helpers.ts
- test/decentraland-ecs/setup-export.spec.ts
Add the status file in export/content path. 
When you start preview mode from export directory and enable Web3, status file is needed.
> fix: add content status endpoint to export

- packages/decentraland-ecs/types/@decentraland/RestrictedActions/index.d.ts
https://github.com/decentraland/sdk/issues/82
This seems that has been resolved at https://github.com/decentraland/explorer/pull/2496, but somehow we lost that commit.
> add missing predefined emote enums

- packages/decentraland-ecs/src/setupProxy.ts
..
When you access to preview mode in HTTPS mode, the unity-renderer fetch fails.
> fix: add mapping .br extension to the same path without it

- packages/@dcl/amd/package-lock.json
- packages/@dcl/amd/package.json
- packages/decentraland-ecs/package.json
- packages/decentraland-ecs/src/decentraland/Events.ts
- packages/decentraland-ecs/types/@decentraland/Players/index.d.ts
- packages/decentraland-ecs/types/dcl/decentraland-ecs.api.json
- packages/decentraland-ecs/types/dcl/decentraland-ecs.api.md
- packages/decentraland-ecs/types/dcl/index-beta.d.ts
- packages/decentraland-ecs/types/dcl/index-full.d.ts
- packages/decentraland-ecs/types/dcl/index.d.ts
+add `onPlayerConnectedObservable` triggered when an avatar spawns
+add `onPlayerDisconnectedObservable` triggered when peer disconnects or comms set avatar as not visible
> feat: add event for peer's avatar connected or disconnected

- packages/@dcl/amd/package-lock.json
- packages/@dcl/amd/package.json
- packages/@dcl/legacy-ecs/package-lock.json
- packages/@dcl/legacy-ecs/package.json
- packages/@dcl/legacy-ecs/src/decentraland/Components.ts
- packages/decentraland-ecs/package.json
- packages/decentraland-ecs/types/dcl/decentraland-ecs.api.json
- packages/decentraland-ecs/types/dcl/decentraland-ecs.api.md
- packages/decentraland-ecs/types/dcl/index-beta.d.ts
- packages/decentraland-ecs/types/dcl/index-full.d.ts
- packages/decentraland-ecs/types/dcl/index.d.ts
having `AttachToAvatarAnchorPointId` in `posix` was throwing that that enum was `undefinied` while executing scene's script
> fix: move `AttachToAvatarAnchorPointId` to ecs

- packages/@dcl/legacy-ecs/src/decentraland/Camera.ts
- packages/decentraland-ecs/types/dcl/decentraland-ecs.api.json
- packages/decentraland-ecs/types/dcl/decentraland-ecs.api.md
- packages/decentraland-ecs/types/dcl/index-beta.d.ts
- packages/decentraland-ecs/types/dcl/index-full.d.ts
- packages/decentraland-ecs/types/dcl/index.d.ts
deprecated `Camera.instance.cameraMode` since there are multiple scenarios where it value could be outdated.
it use should be discouraged in favor of the observable `onCameraModeChangedObservable`
> fix: deprecated `Camera` `cameraMode` and default it to `ThirdPerson`

- packages/decentraland-ecs/types/@decentraland/EnvironmentAPI/index.d.ts
The export enum wasn't exported correctly.
Fix the error
> fix: plaform export from declaration

- packages/decentraland-ecs/src/cli/mock-catalyst/index.ts
Add custom timeouts
Note:
It'd be great if we could catch this proxy error in another middleware, but the libary `http-proxy-middleware` stops the propagation of request even if it fails.
It improves the information and it avoids the browser cancels the requests.
> feat: add warning message when proxy errors

- packages/@dcl/legacy-ecs/src/decentraland/Components.ts
- packages/decentraland-ecs/package.json
- packages/decentraland-ecs/types/dcl/decentraland-ecs.api.json
- packages/decentraland-ecs/types/dcl/decentraland-ecs.api.md
- packages/decentraland-ecs/types/dcl/index-beta.d.ts
- packages/decentraland-ecs/types/dcl/index-full.d.ts
- packages/decentraland-ecs/types/dcl/index.d.ts
- scripts/build.spec.ts
add `excludeIds` field to `AvatarModifierArea` component.
Note: Modifiers won't affect avatars for users which id are contained in `excludeIds`
Can be merged after this PR: https://github.com/decentraland/unity-renderer/pull/1853
> feat: add `excludeIds` field to `AvatarModifierArea`

- packages/@dcl/ecs/package-lock.json
- packages/@dcl/ecs/package.json
- packages/@dcl/ecs/src/engine/component.ts
- packages/@dcl/ecs/src/engine/index.ts
- packages/@dcl/ecs/src/engine/utils.ts
- packages/@dcl/ecs/src/serialization/ByteBuffer/index.ts
- packages/@dcl/ecs/src/serialization/crdt/componentOperation.ts
- packages/@dcl/ecs/src/serialization/wireMessage.ts
- packages/@dcl/ecs/src/systems/crdt/index.ts
- packages/@dcl/ecs/src/systems/crdt/transports/types.ts
- packages/@dcl/ecs/src/systems/crdt/types.ts
- packages/@dcl/ecs/src/systems/crdt/utils.ts
- packages/@dcl/ecs/test/componentOperation.spec.ts
- packages/@dcl/ecs/test/components/TextShape.spec.ts
- packages/@dcl/ecs/test/crdt.spec.ts
- packages/@dcl/ecs/test/engine.spec.ts
- packages/@dcl/ecs/test/transports.spec.ts
When you delete a component, the crdt system try to serialize that component but it doesn't exist anymore.
Now we send an empty Uint8Array if thats the case.
We store all the components into the crdt state, but if there is no transport that needs to send that component we avoid it.
> Fix remove component

- packages/@dcl/ecs/src/serialization/ByteBuffer/index.ts
- packages/@dcl/ecs/src/systems/crdt/index.ts
- packages/@dcl/ecs/src/systems/crdt/transports/rendererTransport.ts
- packages/@dcl/ecs/test/byteBuffer.spec.ts
Add the method `toBinaryCopied()` to ByteBuffer and use it in the transport sending.
If we have more than a `transport`, the data will be changed before being sent.
> fix: send to transport a copied array instead of a reference array. 

- packages/@dcl/sdk/src/cli/mock-catalyst/index.ts
- packages/@dcl/sdk/src/setupProxy.ts
Add the request /active for entities fetching.
Today, kernel uses this new request to fetch scene ids.
https://github.com/decentraland/kernel/pull/349/files#diff-90cd3cdfb62415b9ba7ebe5619ede1358524bfd7387fae63a0fda769f24e895eR43
> fix: preview mode

- packages/@dcl/ecs/src/runtime/MessageBus.ts
- packages/@dcl/react-ecs/etc/react-ecs.api.md
- packages/@dcl/react-ecs/src/index.ts
- scripts/build.spec.ts
- test/build-ecs/fixtures/ecs7-scene/package-lock.json
Fix ecs & react types generated for the playground
We were bundling the incorrect file for ecs7 types.
Also there were some errors on the react-ecs typings, with some missing exports.
> Fix playground/react types

- packages/@dcl/ecs/etc/ecs.api.md
- packages/@dcl/ecs/src/engine/component.ts
- packages/@dcl/sdk/types/ecs7/index.d.ts
Fix the types mismatch between `create` and `createOrReplace`.
Example:
> fix: createOrReplace constructor type

- packages/decentraland-ecs/package.json
This PR upgrades the `@dcl/kernel` dependency to the `next` version, which includes this fix: https://github.com/decentraland/kernel/commit/225796f2a0cfa0bb410aab603afc3c2a53c72d4b
> fix: upgrade kernel

- packages/decentraland-ecs/package.json
This PR upgrades `@dcl/kernel` to the `@next` version and `@dcl/unity-renderer` to the latest rollout version.
> chore: upgrade kernel and unity-renderer

- packages/decentraland-ecs/package.json
To `@dcl/kernel@next` and current rollout `unity-renderer` version
> chore: upgrade kernel renderer

- packages/@dcl/sdk/cli/commands/init/index.ts
- packages/@dcl/sdk/cli/components/fetch.ts
- packages/@dcl/sdk/cli/components/fs.ts
- packages/@dcl/sdk/cli/components/index.ts
- packages/@dcl/sdk/cli/index.ts
- packages/@dcl/sdk/cli/utils/commands.ts
- packages/@dcl/sdk/cli/utils/fs.ts
- test/sdk/cli/commands/init.spec.ts
- test/sdk/cli/utils/fs.spec.ts
This approach to organize code has proven very succesful in separating concerns and enable cleaner code organization and test structure without hacking the internal _and fragile_ module loading of node.js
All servers in Decentraland use this approach, and it is encouraged to keep the same approach for the CLI
> chore: use components approach

- packages/@dcl/sdk/cli/commands/init/index.ts
- packages/@dcl/sdk/cli/commands/init/repos.ts
- packages/@dcl/sdk/cli/components/fs.ts
- packages/@dcl/sdk/cli/index.ts
- packages/@dcl/sdk/cli/utils/fs.ts
- test/sdk/cli/commands/init/index.spec.ts
- test/sdk/cli/utils/fs.spec.ts
New `--move-out` parameter for init command to move files out of the templates folders.
EX: 
1. Clone `https://github.com/decentraland/sdk7-scene-template/archive/refs/heads/main.zip`
2. Extract
3. You will now have a folder with the scene files inside (folder name doesn't matter)
If the user provides the `--move-out` parameter, it will move those files out of that folder, if the user doesn't provide it, it will leave the directory structure as it is.
> Add '--move-out' parametet to init command

- packages/@dcl/ecs/src/engine/input.ts
- packages/@dcl/playground-assets/etc/playground-assets.api.md
- test/ecs/events/isPressed.spec.ts
- test/snapshots/append-value-crdt.ts.crdt
- test/snapshots/billboard.ts.crdt
- test/snapshots/cube-deleted.ts.crdt
- test/snapshots/cube.ts.crdt
- test/snapshots/cubes.ts.crdt
- test/snapshots/pointer-events.ts.crdt
- test/snapshots/schema-components.ts.crdt
- test/snapshots/two-way-crdt.ts.crdt
- test/snapshots/ui.ts.crdt
Fix the most of scene with `isTriggered` usage in the [`sdk7-goerli-plaza`](https://github.com/decentraland-scenes/sdk7-goerli-plaza/actions/runs/4183957143/jobs/7248978072).
This avoids a small breaking change that would need a fix in those scenes and a change of the documentation. 
Until the `Input` API is well defined, the keeps [the known implementation.](https://docs.decentraland.org/creator/development-guide/sdk7/system-based-events/)
@param entity - the entity to query, **ignore for global**
isTriggered: (inputAction: InputAction, pointerEventType: PointerEventType, entity?: Entity) => boolean
> fix: revert isTriggered `entity` param to optional

- packages/@dcl/ecs/src/engine/input.ts
- packages/@dcl/playground-assets/etc/playground-assets.api.md
- test/ecs/events/isPressed.spec.ts
- test/snapshots/append-value-crdt.ts.crdt
- test/snapshots/billboard.ts.crdt
- test/snapshots/cube-deleted.ts.crdt
- test/snapshots/cube.ts.crdt
- test/snapshots/cubes.ts.crdt
- test/snapshots/pointer-events.ts.crdt
- test/snapshots/schema-components.ts.crdt
- test/snapshots/two-way-crdt.ts.crdt
- test/snapshots/ui.ts.crdt
Same as https://github.com/decentraland/js-sdk-toolchain/pull/427
> fix: revert to getInputCommand without mandatory entity

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
- packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/SceneInspector.tsx
- packages/@dcl/inspector/src/components/EntityInspector/TextField/TextField.css
- packages/@dcl/inspector/src/components/EntityInspector/TextField/TextField.tsx
- packages/@dcl/inspector/src/components/EntityInspector/TextField/types.ts
- packages/@dcl/inspector/src/components/EntityInspector/TransformInspector/TransformInspector.tsx
- packages/@dcl/inspector/src/components/EntityInspector/TransformInspector/utils.spec.ts
- packages/@dcl/inspector/src/components/EntityInspector/TransformInspector/utils.ts
- packages/@dcl/inspector/test/data-layer/utils.ts
Fixes https://github.com/decentraland/sdk/issues/703
The issue was formatting the input value within the render of the react component. The conversion from component value into input value should be done within the `fromComponentValueToInput` function provided to the `useComponentInput` hook:
```ts
fromComponentValueToInput(componentValue: ComponentValueType) => InputType
``` 
Otherwise the hook fails to compare the values and fires unnecessary syncs.
I also fixed an issue with the `Scene > Parcels` input which was bound to the wrong value
> fix: inputs

- packages/@dcl/sdk-commands/src/commands/deploy/index.ts
- packages/@dcl/sdk-commands/src/commands/deploy/linker-dapp/api.ts
- packages/@dcl/sdk-commands/src/commands/deploy/utils.ts
- packages/@dcl/sdk-commands/src/logic/config.ts
- test/sdk-commands/commands/deploy/index.spec.ts
- test/sdk-commands/commands/deploy/scene.json.ts
- test/sdk-commands/utils/validations.spec.ts
- ServerComponent was being intialized with the wrong config component
- config component was expecting to have LANDRegistry string always declared.
So when you run sdk-commands deploy if failes because there was no config.LANDRegistry value, and since the default values are already hardcoded on the linker-dapp, we can ommit the requiredString to a readString
> fix deploy command

- packages/@dcl/inspector/src/components/EntityInspector/GltfInspector/GltfInspector.tsx
- packages/@dcl/inspector/src/components/ProjectAssetExplorer/ProjectView.tsx
- packages/@dcl/inspector/src/components/ProjectAssetExplorer/utils.spec.ts
- packages/@dcl/inspector/src/components/ProjectAssetExplorer/utils.ts
- packages/@dcl/inspector/src/lib/logic/once.ts
If the user drops a folder that has only one child across the whole chain of childrens, and that child is an asset, we will use it to create the Gltf component
> feat: support dropping folders on Gltf UI component

- Makefile
- package-lock.json
- package.json
- packages/@dcl/playground-assets/etc/playground-assets.api.md
- packages/@dcl/sdk-commands/package-lock.json
- packages/@dcl/sdk-commands/package.json
- test/ecs/components/UiCanvasInformation.spec.ts
- test/snapshots/development-bundles/testing-fw.test.ts.crdt
- test/snapshots/development-bundles/two-way-crdt.test.ts.crdt
- test/snapshots/package-lock.json
- test/snapshots/production-bundles/append-value-crdt.ts.crdt
- test/snapshots/production-bundles/billboard.ts.crdt
- test/snapshots/production-bundles/composite.ts.crdt
- test/snapshots/production-bundles/cube-deleted.ts.crdt
- test/snapshots/production-bundles/cube.ts.crdt
- test/snapshots/production-bundles/cubes.ts.crdt
- test/snapshots/production-bundles/pointer-events.ts.crdt
- test/snapshots/production-bundles/schema-components.ts.crdt
- test/snapshots/production-bundles/ui.ts.crdt
And update `@dcl/protocol` package
> feat: add UiCanvasInformation component

- packages/@dcl/inspector/src/components/Renderer/Renderer.css
- packages/@dcl/inspector/src/components/Renderer/Renderer.tsx
This PR adds a spinner while the GLTF is being downloaded. It also fixes an issue where the pointer position was captured after the assets where downloaded, instead of the moment the asset is dropped in the renderer. If the asset was big and it took a bit to download, and the user moved the mouse in the mean time, the asset would end up placed at a different position.
Closes https://github.com/decentraland/sdk/issues/717
> feat: loader

- packages/@dcl/inspector/src/components/Renderer/Renderer.tsx
- packages/@dcl/inspector/src/components/Renderer/Warnings/RotationGizmoLocalAlignmentDisabled/RotationGizmoLocalAlignmentDisabled.tsx
- packages/@dcl/inspector/src/components/Renderer/Warnings/RotationGizmoLocalAlignmentDisabled/index.ts
- packages/@dcl/inspector/src/components/Renderer/Warnings/Warning/Warning.css
- packages/@dcl/inspector/src/components/Renderer/Warnings/Warning/Warning.tsx
- packages/@dcl/inspector/src/components/Renderer/Warnings/Warning/index.ts
- packages/@dcl/inspector/src/components/Renderer/Warnings/Warnings.css
- packages/@dcl/inspector/src/components/Renderer/Warnings/Warnings.tsx
- packages/@dcl/inspector/src/components/Renderer/Warnings/index.ts
- packages/@dcl/inspector/src/components/Toolbar/Gizmos/Gizmos.css
- packages/@dcl/inspector/src/components/Toolbar/Gizmos/Gizmos.tsx
- packages/@dcl/inspector/src/lib/babylon/decentraland/gizmo-manager.spec.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/gizmo-manager.ts
Closes: https://github.com/decentraland/sdk/issues/780
This PR adds a warning when the user is using the Rotation gizmo with a local alignment (ie. aligned to the entity) and the entity is not proportionally scaled (which is currently not supported by Babylon), so it forces the gizmo to be world aligned (which works with non-proportional scaled entities).
https://github.com/decentraland/js-sdk-toolchain/assets/2781777/ed61af37-7b09-4674-80ac-542c8f6614d2
I also fixed a few issues that I found testing the alignment feature further:
- The rotation gizmo would not be disabled if the change that made it become non-proportional came from the renderer's engine, is fixed ✅ 
- Disable the rotation gizmo when changing between selected entities (before it would need you to interact with the new …
> feat: gizmo warning

- .github/workflows/ci.yml
- packages/@dcl/ecs/.gitignore
- packages/@dcl/ecs/package.json
- packages/@dcl/ecs/tsconfig.cjs.json
- packages/@dcl/ecs/tsconfig.json
- packages/@dcl/sdk-commands/package-lock.json
- packages/@dcl/sdk-commands/package.json
- packages/@dcl/sdk-commands/src/logic/bundle.ts
- packages/@dcl/sdk-commands/src/logic/composite.ts
- packages/@dcl/sdk/src/index.ts
- test/sdk-commands/blackbox/build-and-export-static.spec.ts
- test/snapshots/development-bundles/static-scene.test.ts.crdt
- test/snapshots/development-bundles/testing-fw.test.ts.crdt
- test/snapshots/development-bundles/two-way-crdt.test.ts.crdt
- test/snapshots/package-lock.json
- test/snapshots/production-bundles/append-value-crdt.ts.crdt
- test/snapshots/production-bundles/billboard.ts.crdt
- test/snapshots/production-bundles/cube-deleted.ts.crdt
- test/snapshots/production-bundles/cube.ts.crdt
- test/snapshots/production-bundles/cubes.ts.crdt
- test/snapshots/production-bundles/pointer-events.ts.crdt
- test/snapshots/production-bundles/schema-components.ts.crdt
- test/snapshots/production-bundles/ui.ts.crdt
- Support CommonJS build for `@dcl/ecs`
- Include `@dcl/ecs` in `sdk-commands`
- At build-time, only composite that can be instanced are added to composite provider
- Double-check with adding a try-catch while instancing the main.composite
> feat: validate composite before include it in the bundle

- packages/@dcl/sdk-commands/src/logic/bundle.ts
Builds are failing on Windows.
> fix: escape backslash for windows path

- packages/@dcl/inspector/src/components/ImportAsset/ImportAsset.css
- packages/@dcl/inspector/src/components/ImportAsset/ImportAsset.tsx
After user clicks on red "Import" button, GLTF is validated by a function provided by Babylon.
File size check is included into validation procedure.
Red border around file name is displayed only when the name is incorrect.
The red cross button which removes an asset is deliberately made always visible.
Closes decentraland/sdk#765
> Validate imported GLTFs.

- package-lock.json
- package.json
- packages/@dcl/sdk-commands/package-lock.json
- packages/@dcl/sdk-commands/package.json
- test/build-ecs/fixtures/ecs7-scene/package.json
- test/build-ecs/fixtures/ecs7-scene/src/index.ts
Related https://github.com/decentraland/protocol/pull/152, https://github.com/decentraland/unity-renderer/pull/5248
> add signed-fetch headers rpc

- packages/@dcl/inspector/src/components/ProjectAssetExplorer/ProjectView.tsx
- packages/@dcl/inspector/src/components/Tree/Tree.css
Closes decentraland/sdk#809.
Fix asset removal. Ensure that context menu items fill all available width (previously it wasn't the case for asset inspector's context menus). Remove context menu from folders in asset folder tree (it is currently useless, as all imports go to root directory anyway).
> fix: repair asset removal

- packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/transform.ts
closes https://github.com/decentraland/sdk/issues/844
There was a race-condition when using the entities scheduled for future re-parenting.
Walkthrough
1. `getOrCreateEntity` on `SceneContext` initializes an `Entity` and pushes it to the `this.#entities` map (**in that order**)
2. When initializing an `Entity`, we are calling `createDefaultTransform`, which checks the scheduled re-parenting list for assigning childs
3. `createDefaultTransform` calls `reparentEntity`, which relies on the list of entities from `SceneContext` to find the desired parent and then clears the scheduled re-parenting list
4.  Since the list of entities on `SceneContext` is incomplete because we are initializing the `Entity`, and this `Entity` is not yet pushed it (thus the importance of the order on step 1), …
> fix: undo not working with re-parenting entities

- packages/@dcl/inspector/src/components/Assets/Assets.tsx
- packages/@dcl/inspector/src/components/EntityInspector/GltfInspector/GltfInspector.tsx
- packages/@dcl/inspector/src/components/EntityInspector/GltfInspector/utils.spec.ts
- packages/@dcl/inspector/src/components/EntityInspector/GltfInspector/utils.ts
- packages/@dcl/inspector/src/components/ImportAsset/ImportAsset.tsx
- packages/@dcl/inspector/src/components/ProjectAssetExplorer/ProjectAssetExplorer.tsx
- packages/@dcl/inspector/src/components/ProjectAssetExplorer/ProjectView.tsx
- packages/@dcl/inspector/src/components/ProjectAssetExplorer/types.ts
- packages/@dcl/inspector/src/components/Renderer/Renderer.tsx
- packages/@dcl/inspector/src/hooks/catalog/useAssetTree.ts
- packages/@dcl/inspector/src/hooks/catalog/useFileSystem.ts
- packages/@dcl/inspector/src/hooks/sdk/useComponentInput.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/SceneContext.ts
- packages/@dcl/inspector/src/lib/data-layer/client/feeded-local-fs.ts
- packages/@dcl/inspector/src/lib/data-layer/host/rpc-methods.ts
fixes assets path on `main.composite` to be always absolute, thus making preview work as expected
> refactor: paths are always absolute

- packages/@dcl/inspector/src/components/Hierarchy/Hierarchy.tsx
- packages/@dcl/inspector/src/components/ProjectAssetExplorer/ProjectView.tsx
- packages/@dcl/inspector/src/components/Tree/ContextMenu/ContextMenu.tsx
- packages/@dcl/inspector/src/components/Tree/Tree.tsx
- packages/@dcl/inspector/src/hooks/sdk/useTree.ts
- packages/@dcl/inspector/src/lib/sdk/operations/duplicate-entity.spec.ts
- packages/@dcl/inspector/src/lib/sdk/operations/duplicate-entity.ts
- packages/@dcl/inspector/src/lib/sdk/operations/index.ts
Closes decentraland/sdk#709.
1. Add "Duplicate entity" option to composite inspector's context menu.
2. This operation creates a copy of entity's subtree, with properly adjusted Transform parenting.
3. Duplicate becomes selected.
> feat: duplicate entity operation

- packages/@dcl/inspector/README.md
- packages/@dcl/inspector/src/components/Hierarchy/Hierarchy.tsx
- packages/@dcl/inspector/src/components/ProjectAssetExplorer/ProjectView.tsx
- packages/@dcl/inspector/src/components/Tree/Tree.tsx
- packages/@dcl/inspector/src/hooks/sdk/useTree.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/camera.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/gizmo-manager.ts
- packages/@dcl/inspector/src/lib/babylon/setup/setup.ts
- packages/@dcl/inspector/src/lib/logic/math.ts
Closes decentraland/sdk#758.
Closes decentraland/sdk#879.
1. When a user double clicks on entity's row in composite inspector, camera transitions to a position where it looks at the center of entity's bounding sphere (including descendants). Position is picked in a way that ensures bounding sphere roughly fitting camera's frustum.
2. Remove boundaries check for translation tool.
3. Change Inspector's skybox color to sky blue.
> feat: center view on entity

- .github/workflows/ci.yml
The E2E test fails in main because there's not cloudflare pages deployment there to test against, so this PR disables it there.
> fix: prevent running e2e test in main

- packages/@dcl/inspector/jest-puppeteer.config.js
- packages/@dcl/inspector/src/components/Assets/Assets.tsx
- packages/@dcl/inspector/src/components/AssetsCatalog/AssetsCatalog.tsx
- packages/@dcl/inspector/src/components/ProjectAssetExplorer/Tile/Tile.tsx
- packages/@dcl/inspector/src/components/Renderer/Renderer.tsx
- packages/@dcl/inspector/test/e2e/Assets.spec.ts
- packages/@dcl/inspector/test/e2e/Hierarchy.spec.ts
- packages/@dcl/inspector/test/e2e/_config.ts
- packages/@dcl/inspector/test/e2e/pageObjects/Assets.ts
- packages/@dcl/inspector/test/e2e/utils/drag-and-drop.ts
This PR adds e2e test for two use cases: dragging an asset from the file system into the canvas and making sure it is added to the entity tree, and also from the builder assets
> chore: add more e2e tests

- packages/@dcl/inspector/src/lib/data-layer/host/index.ts
I need `createEngineContext` and `dumpEngineToComposite` helpers in order to use them from the Builder and easily create a composite using the SDK instead of building the json by hand.
> feat: expose helpers for @dcl/inspector

- packages/@dcl/inspector/src/components/ContexMenu/ContextMenu.tsx
- packages/@dcl/inspector/src/components/ContexMenu/index.ts
- packages/@dcl/inspector/src/components/EntityInspector/GltfInspector/GltfInspector.tsx
- packages/@dcl/inspector/src/components/EntityInspector/TransformInspector/TransformInspector.tsx
- packages/@dcl/inspector/src/components/ProjectAssetExplorer/Tile/Tile.tsx
- packages/@dcl/inspector/src/components/Tree/ContextMenu/ContextMenu.tsx
- packages/@dcl/inspector/src/hooks/sdk/useContextMenu.ts
closes https://github.com/decentraland/sdk/issues/836
> fix: context menu hide on mousedown

- packages/@dcl/inspector/jest.config.js
- packages/@dcl/inspector/src/lib/data-layer/host/scene.ts
- packages/@dcl/inspector/src/lib/data-layer/host/utils/fs-composite-provider.ts
- packages/@dcl/inspector/src/lib/logic/preferences/io.ts
- packages/@dcl/inspector/test/setup.ts
This fixes the issue where the encoding is lost, which happens when Buffers are sent over postMessage because they are received as ArrayBuffers.
> fix: use text decoder for buffers

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
- packages/@dcl/inspector/src/lib/babylon/decentraland/camera.ts
- packages/@dcl/inspector/src/lib/rpc/camera/camera.spec.ts
- packages/@dcl/inspector/src/lib/rpc/camera/client.ts
- packages/@dcl/inspector/src/lib/rpc/camera/server.ts
- packages/@dcl/inspector/src/lib/rpc/camera/types.ts
- packages/@dcl/inspector/src/lib/sdk/context.ts
- packages/@dcl/inspector/src/tooling-entrypoint.ts
This PR adds a camera client that can be used to control the camera and take screenshots when the inspector is used via an iframe, ie:
```ts
import { CameraClient, MessageTransport } from '@dcl/inspector'
const iframe = document.getElementById('inspector')
const transport = new MessageTransport(window, iframe.contentWindow)
const camera = new CameraClient(transport)
await camera.setPosition(0, 1, 0)
await camera.setTarget(8, 1, 8)
const screenshot = await camera.takeScreenshot(1024, 1024)
```
> feat: camera client

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
- packages/@dcl/inspector/src/lib/logic/storage/iframe.ts
- packages/@dcl/inspector/src/lib/rpc/camera/client.ts
- packages/@dcl/inspector/src/lib/rpc/camera/server.ts
This PR bumps the version of `@dcl/mini-rpc` which moves the `Transport` type outside of the `RPC` namespace, this fixes some typing issues.
> fix: bump @dcl/mini-rpc

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
Fixes an issue when using multiple MessageTransport instances in the same document
> fix: bump @dcl/mini-rpc again

- packages/@dcl/sdk-commands/src/commands/pack-smart-wearable/index.ts
This PR fixes the zip file structure for windows.
When a user tries to pack the smart-wearable in windows, the command creates a .zip file with a few folders inside.
> fix: Windows path separator

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
- packages/@dcl/inspector/src/components/Block/Block.tsx
- packages/@dcl/inspector/src/components/Block/types.ts
- packages/@dcl/inspector/src/components/Button/Button.css
- packages/@dcl/inspector/src/components/Container/Container.css
- packages/@dcl/inspector/src/components/Container/Container.tsx
- packages/@dcl/inspector/src/components/Container/types.ts
- packages/@dcl/inspector/src/components/Dropdown/Dropdown.css
- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.css
- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.tsx
- packages/@dcl/inspector/src/components/EntityInspector/MoreOptionsMenu/MoreOptionsMenu.css
- packages/@dcl/inspector/src/components/EntityInspector/MoreOptionsMenu/MoreOptionsMenu.tsx
- packages/@dcl/inspector/src/components/EntityInspector/MoreOptionsMenu/index.ts
- packages/@dcl/inspector/src/components/EntityInspector/TextField/TextField.css
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerAction/TriggerAction.css
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerAction/TriggerAction.tsx
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerAction/index.ts
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerAction/types.ts
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerEvent/TriggerEvent.css
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerEvent/TriggerEvent.tsx
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerEvent/index.ts
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerEvent/types.ts
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerInspector.css
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerInspector.tsx
- packages/@dcl/inspector/src/index.css
This PR updates the Trigger and Action component styles.
It also uses the new trigger schema defined in the package `@dcl/asset-pack to allow handling more than one action per trigger event.
Actions:
Triggers:
> feat: Update inspector components styles

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
- packages/@dcl/inspector/scripts/copy-bin.ts
- packages/@dcl/sdk-commands/package-lock.json
Remove `postinstall`, it was breaking the CLI E2E tests
> chore: remove postinstall

- packages/@dcl/inspector/src/lib/logic/config.ts
Fixes this in `editor-sdk7` with latest sdk:
```
ReferenceError: location is not defined
at getConfig
```
> fix: location not defined

- packages/@dcl/sdk-commands/package-lock.json
- packages/@dcl/sdk-commands/package.json
- packages/@dcl/sdk-commands/src/commands/deploy/utils.ts
- packages/@dcl/sdk-commands/src/logic/project-validations.ts
- test/build-ecs/fixtures/sdk7-humming-birds-sync/src/create-cube.ts
- test/build-ecs/fixtures/sdk7-humming-birds-sync/src/moving-platforms.ts
Running `npm srtart` was doing a `npm install @dcl/js-runtime`, and this removes all `npm link`. So if you were running a library inside your scene, the link was being removed.
Remove queryParams from linker-dapp, because we were already fetching this via api request and if the URL was too big then the linker-dapp fails to load
> start & deploy improvements

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerCondition/TriggerCondition.tsx
- packages/@dcl/inspector/src/lib/sdk/operations/add-child.ts
This PR fixes conditions by replacing `{selfEntity}` on drag n dropped items. It also hides the `operation` dropdown when there are less than 2 conditions, since it's not necessary on that scenario.
> fix: trigger conditions on drag n drop

- packages/@dcl/sdk-commands/package-lock.json
- packages/@dcl/sdk-commands/package.json
- packages/@dcl/sdk-commands/src/commands/quests/index.ts
- packages/@dcl/sdk-commands/src/commands/quests/types.ts
- packages/@dcl/sdk-commands/src/commands/quests/utils.ts
This PR fixes the `quests` command that is failing in the last version due to `@dcl/quests-client` lib that uses ESM for its modules
`IMPORTANT NOTE: this is a temporal patch to avoid the usage of `@dcl/quests-client` package, until it get fixed and this changes can be reverted`
> fix: remove quests-client due to ESM

- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlaySoundAction/PlaySoundAction.tsx
- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlaySoundAction/types.ts
- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlaySoundAction/utils.ts
The `play_sound` action was working fine with pre-popullated values from smart items, but when creating an action from scratch it throws due to undefined values, because the typings were wrong (not using `Partial`).
This PR fixes that.
> fix: play_sound undefined values

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.tsx
- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlayAnimationAction/PlayAnimationAction.css
- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlayAnimationAction/PlayAnimationAction.tsx
- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlayAnimationAction/index.ts
- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlayAnimationAction/types.ts
- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlayAnimationAction/utils.ts
- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlaySoundAction/PlaySoundAction.tsx
- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/TweenAction/utils.ts
- packages/@dcl/inspector/src/lib/sdk/operations/add-asset.ts
This PR adds support for the `attach_to_player` and `detach_from_player` actions, adds support for the `loop` property in `play_animation`, and adds support for the new `stop_animation` and `stop_sound` actions.
> feat: attach/detach, loop animation, stop animation/sound

- packages/@dcl/sdk-commands/src/commands/deploy/index.ts
- packages/@dcl/sdk-commands/src/logic/scene-validations.ts
- test/sdk-commands/utils/scene-validation.spec.ts
closes https://github.com/decentraland/sdk/issues/951
> add: warning for missing keys on scene.json

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
This PR updates `@dcl/asset-packs` to a version that can be used from VSCode
> feat: add support for vscode

- packages/@dcl/inspector/src/components/EntityInspector/MoreOptionsMenu/MoreOptionsMenu.tsx
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerAction/TriggerAction.css
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerAction/TriggerAction.tsx
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerCondition/TriggerCondition.css
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerCondition/TriggerCondition.tsx
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerInspector.tsx
- packages/@dcl/inspector/src/hooks/useArrayState.ts
This PR fixes a CSS error with triggers that don't allow users to remove elements.
Closes: https://github.com/decentraland/sdk/issues/957
> fix: Triggers css width

- packages/@dcl/inspector/src/hooks/sdk/useComponentInput.ts
Fixes https://github.com/decentraland/sdk/issues/954
The issues was that the initial state of `isValid` was `false`, so it was always initially rendered with an error, then once the validation happened it was rendered without the error, but you could see the red border for a split second.
> fix: gltf path error

- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.tsx
- packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerEvent/TriggerEvent.tsx
This PR adds a text map for Action and Trigger types.
Closes https://github.com/decentraland/sdk/issues/969
> fix: Add text map for Action and Trigger types

- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/TweenAction/TweenAction.tsx
This PR fixes the tween dropdown text styles.
> fix: Tween titles

- packages/@dcl/inspector/src/components/ui/WalletField/WalletField.tsx
- packages/@dcl/inspector/src/components/ui/WalletField/index.ts
- packages/@dcl/inspector/src/components/ui/WalletField/types.ts
- packages/@dcl/inspector/src/lib/logic/ethereum.ts
This PR adds the util component `WalletField`.
This component is a wrapper of the TextField, adding validation for ethereum addresses.
Closes https://github.com/decentraland/sdk/issues/984
> feat: WalletField component

- packages/@dcl/inspector/src/components/ui/Dropdown/Dropdown.tsx
This PR fixes the dropdown search flow.
- Hide the search text field when the dropdown doesn't have available options
- Show an empty message when there are no results for the search
> fix: Dropdown search empty message

- packages/@dcl/ecs/src/systems/raycast.ts
- test/ecs/events/raycastHelperSystem.spec.ts
The problem reported in the related issue was happening because if a very short interval is used to register a non-continuous raycast with the helper raycst system, it may happen that the raycast is removed from the entity (when the raycast result is read by the helper system) and in the same frame a new raycast is registered on the same entity, thus resulting in only a `putComponent()` instruction coming out  of the scene runtime, in that situation the client never gets the `removeComponent()` call, and the new raycast registration is never effective, stopping any new raycast result on the entity.
Issue: https://github.com/decentraland/sdk/issues/993
* Added 1 frame delay when registering raycasts using the helper system
* Added pertinent test
> fix: raycast helper system ray registration on short interval

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/SetVisibilityAction/SetVisibilityAction.tsx
- packages/@dcl/inspector/src/components/EntityInspector/VisibilityComponentInspector/VisibilityComponentInspector.tsx
- packages/@dcl/sdk-commands/package-lock.json
This PR updates the colliders dropdown by default to `none` when setting an action with `visibility: false`
Closes: https://github.com/decentraland/sdk/issues/981
Depends on: https://github.com/decentraland/asset-packs/pull/86
> fix: Colliders when settings visibility

- scripts/rpc-api-generation/index.ts
- scripts/utils/stringParser.ts
Include comment blocks from the protocol specification into the `apis.d.ts` file
Before 
```typescript
// Function declaration section
export function getRealm(body: GetRealmRequest): Promise<GetRealmResponse>;
export function getWorldTime(body: GetWorldTimeRequest): Promise<GetWorldTimeResponse>;
export function readFile(body: ReadFileRequest): Promise<ReadFileResponse>;
export function getSceneInformation(body: CurrentSceneEntityRequest): Promise<CurrentSceneEntityResponse>;
```
Now
```typescript
// Function declaration section
/** Provides information about the current realm */
export function getRealm(body: GetRealmRequest): Promise<GetRealmResponse>;
/**
* Provides information about the Decentraland Time, which is coordinated
* across players.
*/
export function getWorldTime(body: …
```
> chore: include comment blocks in apis' methods

- packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/gltf-container.ts
This fixes some issues in Templates where the colliders are named like `_collider.01` and where not properly removed in the inspector, even though they are hidden by the client.
> fix: hide colliders

- packages/@dcl/sdk/package.json
Bumping explorer package to point to its [latest release](https://github.com/decentraland/unity-renderer/pull/6040)
> chore: bump explorer package

- packages/@dcl/inspector/src/components/EntityInspector/EntityInspector.tsx
- packages/@dcl/inspector/src/components/Tree/ActionArea/ActionArea.css
- packages/@dcl/inspector/src/components/Tree/ActionArea/ActionArea.tsx
- packages/@dcl/inspector/src/components/Tree/ActionArea/index.ts
- packages/@dcl/inspector/src/components/Tree/Tree.css
- packages/@dcl/inspector/src/components/Tree/Tree.tsx
- packages/@dcl/inspector/src/hooks/sdk/useEntityComponent.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/EcsEntity.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/SceneContext.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/editorComponents/hide.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/editorComponents/lock.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/editorComponents/selection.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/gizmo-manager.ts
- packages/@dcl/inspector/src/lib/sdk/components/index.ts
- packages/@dcl/inspector/src/lib/sdk/operations/add-component.spec.ts
- packages/@dcl/inspector/src/lib/sdk/operations/add-component.ts
This PR adds the `Lock` and `Hide` components to let users `lock` and `hide` entities in the inspector.
https://github.com/decentraland/js-sdk-toolchain/assets/3170051/55d70d77-3795-4e78-a0db-af33ada882fb
Closes: https://github.com/decentraland/sdk/issues/1067
> feat: Add lock and hide inspector components

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
This needs to be a dependency because it's used by the entrypoint of the `@dcl/inspector` used by the `@dcl/sdk-commands` package (to configure the RPC of the CLI)
> fix: added ts-deepmerge to dependencies to fix entrypoint

- packages/@dcl/inspector/src/lib/sdk/components/index.ts
Fixes the issue with old scenes throwing `Error: inspector::Scene is not defined and there is no schema to define it.`
> fix: add legacy schema for retrocompat

- packages/@dcl/inspector/src/components/Toolbar/Gizmos/Gizmos.tsx
- packages/@dcl/inspector/src/hooks/editor/useSnap.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/gizmo-manager.spec.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/gizmo-manager.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/gizmo-patch.ts
- packages/@dcl/inspector/src/lib/babylon/setup/input.ts
- packages/@dcl/inspector/src/lib/utils/gizmo.ts
This PR adds assets planar movement.
https://github.com/decentraland/js-sdk-toolchain/assets/3170051/abc52747-0821-4ed6-90f4-9526cbd41d15
Closes: https://github.com/decentraland/sdk/issues/1068
Fixes: https://github.com/decentraland/sdk/issues/1075
> feat: Add planar movement

- packages/@dcl/inspector/src/components/Renderer/Renderer.tsx
- packages/@dcl/inspector/src/components/Renderer/Shortcuts/Shortcuts.css
- packages/@dcl/inspector/src/components/Renderer/Shortcuts/Shortcuts.tsx
- packages/@dcl/inspector/src/components/Renderer/Shortcuts/index.ts
- packages/@dcl/inspector/src/components/Renderer/Shortcuts/types.ts
- packages/@dcl/inspector/src/components/Toolbar/Gizmos/Gizmos.tsx
- packages/@dcl/inspector/src/hooks/useHotkey.ts
- packages/@dcl/inspector/src/hooks/useOutsideClick.ts
This PR adds a toolbar in the render to show hotkeys help.
Also add the following new hotkeys:
- `M` to activate the positioning gizmo
- `R` to activate the rotating gizmo
- `X` to activate the scaling gizmo
- `ctrl` + `D` to duplicate entities
https://github.com/decentraland/js-sdk-toolchain/assets/3170051/854d57c1-61aa-4e30-8947-f42391be8079
Closes: https://github.com/decentraland/sdk/issues/1072
Fixes: https://github.com/decentraland/sdk/issues/1076
> feat: Add shortcuts component

- packages/@dcl/inspector/src/components/Renderer/Renderer.tsx
- packages/@dcl/inspector/src/components/Toolbar/Gizmos/Gizmos.tsx
- packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/gltf-container.ts
This PR adds a spinner while the entity is loaded from the rpc-layer.
https://github.com/decentraland/js-sdk-toolchain/assets/3170051/3f3e6c31-0128-4a63-a56f-cf74b0d5ca59
Closes: https://github.com/decentraland/sdk/issues/1073
> feat: Add spinner when loading assets

- packages/@dcl/inspector/src/components/Renderer/Renderer.tsx
- packages/@dcl/inspector/src/components/Tree/ActionArea/ActionArea.tsx
This PR adds tracking for adding/removing the components: `Lock` and `Hide`.
Closes: https://github.com/decentraland/sdk/issues/1074
> feat: Track when adding/removing components: lock and hide

- packages/@dcl/dcl-rollup/ecs.config.ts
- packages/@dcl/dcl-rollup/libs.config.ts
- packages/@dcl/dcl-rollup/package-lock.json
- packages/@dcl/dcl-rollup/package.json
- packages/@dcl/dcl-rollup/tsconfig.json
- packages/@dcl/legacy-ecs/package-lock.json
- packages/@dcl/legacy-ecs/package.json
- packages/@dcl/legacy-ecs/src/decentraland/Components.ts
- packages/@dcl/legacy-ecs/src/ecs/Component.ts
- packages/@dcl/legacy-ecs/src/ecs/Engine.ts
- packages/@dcl/legacy-ecs/src/ecs/Observable.ts
- packages/@dcl/legacy-ecs/src/ecs/helpers.ts
- packages/@dcl/legacy-ecs/tsconfig.json
- packages/decentraland-ecs/types/dcl/decentraland-ecs.api.json
- packages/decentraland-ecs/types/dcl/decentraland-ecs.api.md
- packages/decentraland-ecs/types/dcl/index-beta.d.ts
- packages/decentraland-ecs/types/dcl/index-full.d.ts
- packages/decentraland-ecs/types/dcl/index.d.ts
- scripts/build.spec.ts
- scripts/common.ts
- scripts/prepare.spec.ts
This PR updates the `legacy-ecs` package to be transpiled as an ESM module.
> fix: Update legacy-ecs package

- packages/@dcl/inspector/src/components/Renderer/Shortcuts/Shortcuts.css
- packages/@dcl/inspector/src/components/Renderer/Shortcuts/Shortcuts.tsx
This PR adds a new item to the shortcuts help guide.
- Roate Camera | `Left Mouse Buton` + `Drag`
> feat: Add Rotate camera shortcut help

- packages/@dcl/inspector/src/components/AssetsCatalog/AssetsCatalog.tsx
This PR fixes the search-matching logic.
https://github.com/decentraland/js-sdk-toolchain/assets/3170051/10b5df0b-c954-47dd-86da-2b8de24b4a6d
> fix: Search items

- packages/@dcl/inspector/src/components/EntityInspector/TransformInspector/utils.ts
Avoid using negative values for rotation, wrap them around 360
> feat: wrap rotation

- packages/@dcl/inspector/src/components/Renderer/Metrics/Metrics.css
- packages/@dcl/inspector/src/components/Renderer/Metrics/Metrics.tsx
- packages/@dcl/inspector/src/components/Renderer/Metrics/index.ts
- packages/@dcl/inspector/src/components/Renderer/Metrics/types.ts
- packages/@dcl/inspector/src/components/Renderer/Metrics/utils.ts
- packages/@dcl/inspector/src/components/Renderer/Renderer.css
- packages/@dcl/inspector/src/components/Renderer/Renderer.tsx
- packages/@dcl/inspector/src/lib/babylon/decentraland/layout-manager.ts
- packages/@dcl/inspector/src/lib/utils/scene.ts
This PR adds the scene limits metrics.
https://docs.decentraland.org/creator/development-guide/sdk7/scene-limitations/#scene-limitation-rules
> feat: Add Metrics Limits overlay

- packages/@dcl/inspector/src/components/ui/TextField/TextField.tsx
- packages/@dcl/inspector/src/components/ui/utils.ts
- packages/@dcl/inspector/src/hooks/sdk/useTree.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/gizmo-manager.ts
- packages/@dcl/inspector/src/lib/utils/debounce.ts
This PR validates that entities have a `TransformComponent` before updating the position when using the free gizmo.
> fix: PointerUp update transform for entities with not transform component

- packages/@dcl/inspector/src/components/Renderer/Metrics/Metrics.tsx
Use `getOrNull` to get `Scene` component and check it is not null. This was throwing an error on the VSCode extension, because the `<Metrics />` react component was being rendered and the `handleUpdateSceneLayout` was being called before the data layer was initialized, resulting in an Error.
> fix: check if scene component is null

- packages/@dcl/playground-assets/etc/playground-assets.api.md
- packages/@dcl/react-ecs/src/components/Button/index.tsx
- packages/@dcl/react-ecs/src/components/Dropdown/index.tsx
- packages/@dcl/react-ecs/src/components/Dropdown/types.ts
- packages/@dcl/react-ecs/src/components/Input/index.tsx
- packages/@dcl/react-ecs/src/components/Input/types.ts
- packages/@dcl/react-ecs/src/components/Label/index.tsx
- packages/@dcl/react-ecs/src/components/Label/types.ts
- packages/@dcl/react-ecs/src/components/Label/utils.ts
- packages/@dcl/react-ecs/src/components/index.tsx
- packages/@dcl/react-ecs/src/components/types.ts
- packages/@dcl/react-ecs/src/components/uiTransform/types.ts
- packages/@dcl/react-ecs/src/components/uiTransform/utils.ts
- packages/@dcl/react-ecs/src/components/utils.ts
- test/react-ecs/label.spec.tsx
- test/react-ecs/transform.spec.tsx
Copy of CSS `calc` function but just for `vw/vh` units
> Add scaleFontSize helper

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
- packages/@dcl/sdk-commands/package-lock.json
- packages/@dcl/sdk-commands/src/commands/build/index.ts
- packages/@dcl/sdk-commands/src/logic/bundle.ts
- packages/@dcl/sdk-commands/src/logic/config.ts
- packages/@dcl/sdk-commands/src/logic/project-validations.ts
- test/sdk-commands/commands/build/index.spec.ts
With this PR is not mandatory to import and install the @dcl/asset-pack lib for the editor scenes.
The sdk-commands does all this at build-time in the background using the asset-pack version that the inspector used to build the scene.
So this way we don't have mismatched of @dcl/asset-packs version. (The inspector already has the asset-packs lib, and the scene could have another version that could lead into mysterious bugs )
```ts
import { engine } from '@dcl/sdk/ecs'
import { initAssetPacks } from '@dcl/asset-packs/dist/scene-entrypoint'
initAssetPacks(engine)
function main() {}
```
```ts
import { engine } from '@dcl/sdk/ecs'
function main() {}
```
> auto install & import asset-packs for editor scenes

- packages/@dcl/ecs/src/engine/index.ts
- packages/@dcl/ecs/src/engine/types.ts
- packages/@dcl/ecs/src/index.ts
- packages/@dcl/ecs/src/systems/tween.ts
- packages/@dcl/playground-assets/etc/playground-assets.api.md
- packages/@dcl/sdk-commands/package-lock.json
- test/build-ecs/fixtures/sdk7-humming-birds-sync/src/hummingBird.ts
- test/ecs/events/tween.spec.ts
This PR exports the method: `createTweenSystem` to be used in the `asset-packs` project.
> feat: Export create tween system

- packages/@dcl/inspector/src/lib/babylon/decentraland/EcsEntity.spec.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/EcsEntity.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/SceneContext.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/gltf-container.ts
Fixes: https://github.com/decentraland/sdk/issues/1091
The bug was introduced by this fix: https://github.com/decentraland/js-sdk-toolchain/pull/777.
This PR also fixes an issue with the spinners that were not placed correctly if the entity was nested.
> fix: nested entities

- packages/@dcl/inspector/src/lib/babylon/decentraland/EcsEntity.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/gizmo-manager.spec.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/gltf-container.ts
Currently, when an entity is nested under the Player or Camera, it is hidden from the scene renderer (Babylon). That works fine when reparenting, but when the scene is loaded for the first time (like after refreshing the editor), all the GLTFContainers are loaded into the scene, no matter where the entity is nested under.
This PR changes the `loadGltf` function to check the root of the entity tree branch, and if it's not the RootEntity, it hides the model. We still load the model, otherwise if this entity is later nested under the RootEntity, the `entity.setVisibility(true)` whould not work, because the model is not loaded.
> fix: hide GLTFs on entities nested under the Camera or Player

- packages/@dcl/inspector/src/components/Renderer/Renderer.tsx
- packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/gltf-container.ts
The previous implementation was assuming that when the root could not be determined (ie. it was `null`) the model should be hidden. 
This was because when refreshing a scene, the `loadGLTF` method is called from two places: the `Renderer.tsx` and the `putGltfContainerComponent`, and the calls from the `Renderer.tsx` where prior to the composite being instantiated, thus the root could not be determined due to the Nodes component not being loaded into the engine, and the calls from the `putGltfContainerComponent` happend after the Nodes component was already loaded.
But that assumption was wrong, and sometimes the `putGltfContainerComponent` is called also before the Nodes component is loaded, so the root is never able to be determined (this depends on the order of the component keys in the …
> fix: prevent race condition between loading Nodes component and GLTFs

- packages/@dcl/inspector/src/components/EntityInspector/TextShapeInspector/utils.spec.ts
- packages/@dcl/inspector/src/lib/data-layer/client/feeded-local-fs.ts
- packages/@dcl/inspector/src/lib/data-layer/host/utils/migrations/build-nodes-hierarchy.ts
Remove "Magic Cube" from autogenerated `main.composite` on workspaces that don't have a composite when using the `@dcl/inspector`
This caused an issue that if you open a non-Editor project with the Editor, and then open the Visual Editor, the inspector would autogenerate a composite with the Magic Cube for that project.
> fix: remove magic cube

- packages/@dcl/sdk/src/observables.ts
merge when https://github.com/decentraland/unity-renderer/pull/6163 reaches prod.
>  [DO NOT MERGE] remove old observabels logic

- packages/@dcl/inspector/src/components/ImportAsset/ImportAsset.css
- packages/@dcl/inspector/src/components/ImportAsset/ImportAsset.tsx
- packages/@dcl/inspector/src/components/Renderer/Renderer.tsx
- packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/gltf-container.ts
- packages/@dcl/inspector/src/redux/data-layer/index.ts
- packages/@dcl/inspector/src/redux/data-layer/sagas/connect.spec.ts
Fixes https://github.com/decentraland/dapps-issues/issues/140
This PR changes the ImportAsset modal to allow importing assets with a name that already exists. 
If a file with that name exists, it will show a warning letting the user know that they will override that file.
This PR also changes the Renderer so when the files change, it will ONLY reload the gltf models that have been updated, instead of every gltf container in the scene.
> fix: import duplicated file name

- packages/@dcl/inspector/src/components/Renderer/Renderer.tsx
This PR fixes the loading assets when importing from the catalog.
Closes: https://github.com/decentraland/sdk/issues/1124
> fix: Load assets when importing from the catalog

- package-lock.json
- package.json
- packages/@dcl/playground-assets/etc/playground-assets.api.md
- packages/@dcl/react-ecs/src/components/Button/index.tsx
- packages/@dcl/react-ecs/src/components/Label/index.tsx
- packages/@dcl/react-ecs/src/components/Label/types.ts
- packages/@dcl/react-ecs/src/components/Label/utils.ts
- packages/@dcl/react-ecs/src/components/index.tsx
- packages/@dcl/sdk-commands/package-lock.json
- packages/@dcl/sdk-commands/package.json
- scripts/prepare.spec.ts
- test/ecs/components/UiText.spec.ts
- test/react-ecs/label.spec.tsx
> feat: add text wrap to ui

- packages/@dcl/inspector/src/lib/babylon/decentraland/EcsEntity.spec.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/EcsEntity.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/gltf-container.ts
- packages/@dcl/inspector/src/lib/babylon/setup/setup.ts
- test/snapshots/package-lock.json
This PR refactors the bounding box info and the outside layout material generation to avoid cases when nested entities behave unexpectedly.
Closes: https://github.com/decentraland/sdk/issues/1119
Closes: https://github.com/decentraland/sdk/issues/1101
> fix: Refactor get bounding box info and outside layout material generation

- packages/@dcl/react-ecs/src/components/Label/utils.ts
- test/react-ecs/label.spec.tsx
Make ui text wrap by default if the property is missing.
> chore: re-introduce uitext wrap

- packages/@dcl/inspector/src/lib/data-layer/host/scene.ts
- packages/@dcl/inspector/src/lib/data-layer/host/stream.ts
Every time we close the `@dcl/inspector` and it was connected via websocket, the data layer prints the following error:
```
Faile to consume stream from data layer  Error: RPC Transport closed
at /Users/mostro/Code/test-text-shape/node_modules/@dcl/rpc/dist/stream-protocol.js:65:23
at /Users/mostro/Code/test-text-shape/node_modules/mitt/dist/mitt.js:1:255
at Array.map (<anonymous>)
```
This PR ignores that particular error.
> fix: avoid annoying error message when websocket disconnects

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
This upgrades to `decentraland-ui` to `v6.5.3` which contains the following fixed dependency: https://github.com/decentraland/ui-env/pull/10
> fix: upgrade decentraland-ui

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
Upgrade `@dcl/asset-packs` to fix cyclic dependency.
BEFORE:
AFTER:
> fix: cyclic dependency

- packages/@dcl/sdk-commands/package-lock.json
- packages/@dcl/sdk-commands/src/commands/build/index.ts
- packages/@dcl/sdk-commands/src/logic/project-validations.ts
@dcl/asset-packs is already installed inside the @dcl/inspector.
@dcl/inspector is installed via @dcl/sdk-commands
@dcl/sdk-commands is installed via @dcl/sdk
So there is no need to install the asset-packs again, is already there. 
Also it fixes the unlink of npm packages every time you run `npm start`.
> remove install of asset-pack

- packages/@dcl/inspector/src/components/Renderer/Renderer.tsx
- packages/@dcl/inspector/src/hooks/sdk/useTree.ts
- packages/@dcl/inspector/src/lib/sdk/operations/duplicate-entity.ts
closes https://github.com/decentraland/sdk/issues/1131
> fix selection after duplicating (PR #1000 🚀)

- packages/@dcl/sdk-commands/src/logic/bundle.ts
Having `node` installed was previously assumed be since the user would be running `npm start` on a scene to preview it.
Since we are now running sdk-commands from within another processes (creator-hub, etc), the OS where we are running those processes might not have `node` installed, so we need to run sub-processes using the bundled node executable (or the original executable caller).
> fix node spawn process

- package-lock.json
- package.json
- packages/@dcl/playground-assets/etc/playground-assets.api.md
- packages/@dcl/sdk-commands/package-lock.json
- packages/@dcl/sdk-commands/package.json
- packages/@dcl/sdk/src/network/entities.ts
- packages/@dcl/sdk/src/network/message-bus-sync.ts
- packages/@dcl/sdk/src/network/state.ts
- packages/@dcl/sdk/src/network/utils.ts
- packages/@dcl/sdk/src/players/index.ts
- test/ecs/components/RealmInfo.spec.ts
Send CRDT State when a player enters the scene. _Before was done the first time the scene started._
Send the CRDT State with the userId that needs to receive that message. So if a player recieces a CRDT state that is not mean to him, it can ignore it.
_Before the user that enters requested the crdt state, and everyone answer to that request. Now we send it without the REQ from the user._
~Add a delay of 2s when the player enters the scene to wait till comms is initalized (TODO: add a component or API for this)~
Use the PBRealmInfo component to know when the user is connected to comms, and then ask for the state
If a player leaves the scene, but the scene is still running in the background (because of hte load of radius), mark the scene as not initialized, so when the player enters again …
> send initial state when the player joins the scene

- packages/@dcl/inspector/src/components/EntityInspector/EntityHeader/EntityHeader.css
- packages/@dcl/inspector/src/components/EntityInspector/EntityHeader/EntityHeader.tsx
- packages/@dcl/inspector/src/components/Tree/Edit/Edit.tsx
- packages/@dcl/inspector/src/hooks/sdk/useEntityComponent.ts
- packages/@dcl/inspector/src/lib/sdk/tree.ts
closes https://github.com/decentraland/sdk/issues/1143
> add entity Name editing from EntityInspector

- packages/@dcl/inspector/src/components/EntityInspector/MaterialInspector/Texture/utils.ts
- packages/@dcl/inspector/src/components/EntityInspector/VideoPlayerInspector/utils.ts
- packages/@dcl/inspector/src/lib/sdk/components/index.ts
closes https://github.com/decentraland/sdk/issues/1155
closes https://github.com/decentraland/sdk/issues/1138
closes https://github.com/decentraland/sdk/issues/1133
> Fix some bugs

- packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/Layout.tsx
- packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/utils.spec.ts
- packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/utils.ts
closes https://github.com/decentraland/creator-hub/issues/207
> fix (and reworkit a little bit) the Layout Grid

- package-lock.json
- package.json
- packages/@dcl/playground-assets/etc/playground-assets.api.md
- packages/@dcl/sdk-commands/package-lock.json
- packages/@dcl/sdk-commands/package.json
- test/ecs/components/Material.spec.ts
Addresses the SDK part of [issue #240](https://github.com/decentraland/creator-hub/issues/240)
Related PRs:
E@: https://github.com/decentraland/unity-explorer/pull/2482
Protocol: https://github.com/decentraland/protocol/pull/223
> chore: move alpha_texture from PBRMaterial to UnlitMaterial

- packages/@dcl/inspector/src/lib/data-layer/host/utils/component.ts
- packages/@dcl/sdk-commands/src/components/analytics.ts
- test/sdk-commands/utils/analytics.spec.ts
Added `appId` and `projectId` properties to events from the CLI, so we can identify when they come from the Creator Hub.
I also made the inspector save in the `scene.json` the `source` property if it has the appId and projectId set in the config, so the deployed scene can also be identified as created with the creator-hub (or other apps that use the inspector).
> chore: Creator Hub analytics

- package-lock.json
- package.json
- packages/@dcl/ecs/src/systems/events.ts
- packages/@dcl/inspector/src/components/EntityInspector/PointerEventsInspector/PointerEventsInspector.tsx
- packages/@dcl/inspector/src/components/EntityInspector/PointerEventsInspector/utils.spec.ts
- packages/@dcl/inspector/src/components/EntityInspector/PointerEventsInspector/utils.ts
- packages/@dcl/playground-assets/etc/playground-assets.api.md
- packages/@dcl/sdk-commands/package-lock.json
- packages/@dcl/sdk-commands/package.json
- test/ecs/components/PointerEvents.spec.ts
- test/ecs/events/system.spec.ts
- test/snapshots/package-lock.json
* Implements support for new `PointerEvents` `showHighlight` property
* Fixed bug existent bug for the case of using `pointerEventsSystem.onPointerDown()` without any of the pointer event optional properties (those entities weren't clickable before this PR)
Related PRs:
- https://github.com/decentraland/protocol/pull/224
- https://github.com/decentraland/unity-explorer/pull/2651
> feat: pointer event toggle highlight

- packages/@dcl/inspector/src/components/EntityInspector/SmartItemBasicView/SmartItemBasicView.tsx
- packages/@dcl/inspector/src/hooks/sdk/useHasComponent.ts
This PR fixes two unrelated issues that have been introduced on this commit: https://github.com/decentraland/js-sdk-toolchain/commit/cf41aed618c96b2b4bfc60c7a7a6e42dfb89c701
1) The `SmartItemBasicView` was using a `useMemo` that was not being called on every render, due to an early return if the entity had no Config component. Hooks need to be called allways on every render to work properly, so this was causing runtime errors. I refactored it to instead of using `useHasComponent` to return early, it just checks for a null config.
2) The `useHasComponent` hook would cache values when switching between different entities. I added an effect to refresh the value if the entity changes. This caused the issue where switching from a smart item to a regular item, it would keep the 'Enable Advanced …
> fix: config issues

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
- packages/@dcl/inspector/src/components/AssetsCatalog/Asset/Asset.tsx
- packages/@dcl/inspector/src/components/EntityInspector/SmartItemBasicView/VideoView/VideoView.tsx
- packages/@dcl/inspector/src/components/EntityInspector/VideoPlayerInspector/VideoPlayerInspector.tsx
- packages/@dcl/inspector/src/components/ProjectAssetExplorer/ProjectView.tsx
- packages/@dcl/inspector/src/components/ProjectAssetExplorer/types.ts
- packages/@dcl/inspector/src/components/Renderer/Renderer.tsx
- packages/@dcl/inspector/src/components/ui/FileUploadField/FileUploadField.tsx
- packages/@dcl/inspector/src/lib/logic/catalog.ts
- packages/@dcl/inspector/src/lib/sdk/drag-drop.spec.ts
- packages/@dcl/inspector/src/lib/sdk/drag-drop.ts
- packages/@dcl/inspector/src/lib/sdk/operations/add-asset/index.ts
This PR refactor the `addAsset` operation to work with the new `@dcl/asset-packs` asset format, which uses composites instead of the custom format.
It also adds support for multiple entities per item, since the composite supports multiple entities. When multiple entities are present, a main entity will be created (this one will have the Transform in the position the user selected) and the item's entities will be added as children of that main entity. When a single entity is used and it's id is 0, then those components will be added to the main entities (to avoid having the main entity with a single child when only 1 entity is needed. which is the case of the current smart items).
Finally, it refactors the ProjectAssets and BuilderAssets into LocalAssets and CatalogAssets, which match …
> refactor: composite

- packages/@dcl/inspector/src/components/CustomAssets/ContextMenu/ContextMenu.ts
- packages/@dcl/inspector/src/lib/data-layer/host/rpc-methods.ts
- packages/@dcl/inspector/src/lib/data-layer/proto/data-layer.proto
- packages/@dcl/inspector/src/lib/logic/analytics.ts
- packages/@dcl/inspector/src/redux/data-layer/sagas/create-custom-asset.spec.ts
- packages/@dcl/inspector/src/redux/data-layer/sagas/create-custom-asset.ts
This PR adds analytics tracking for custom item operations in the Inspector package, including creation, deletion, and renaming of custom items.
Added new event types in `analytics.ts`:
- `CREATE_CUSTOM_ITEM`: Tracks when a custom item is created
- `DELETE_CUSTOM_ITEM`: Tracks when a custom item is deleted  
- `RENAME_CUSTOM_ITEM`: Tracks when a custom item is renamed
Each event includes relevant metadata:
- `CREATE_CUSTOM_ITEM`: 
- `itemId`: Unique identifier for the item
- `itemName`: Name of the item
- `resourceCount`: Number of resources in the item
- `isSmart`: Whether the item is a smart item
- `DELETE_CUSTOM_ITEM`:
- `itemId`: Unique identifier for the item
- `RENAME_CUSTOM_ITEM`:
- `itemId`: Unique identifier for the item
> chore: added analytics for custom items

- packages/@dcl/inspector/src/components/Assets/Assets.css
- packages/@dcl/inspector/src/components/FileInput/FileInput.tsx
- packages/@dcl/inspector/src/components/ImportAsset/Error/Error.tsx
- packages/@dcl/inspector/src/components/ImportAsset/utils.ts
- packages/@dcl/inspector/src/lib/data-layer/client/feeded-local-fs.ts
- **Enhancements to Button Styles:**
- Added:
- `padding: 8px 9px;`
- `font-weight: 600;`
- `border-radius: 6px;`
- Increased `stroke-width` for the first button's SVG.
- **Input Reset After File Selection:**
- Added a comment to clarify the purpose of resetting the input value.
- Reset the input value to allow re-selection of the same file.
- **Simplified Error Handling:**
- Used optional chaining for error type checking.
- Updated rendering logic to display error messages only if an error exists.
- **Error Code Update:**
- Added a new error code: 
- `'VALUE_NOT_IN_RANGE'`
- **Refactoring of `getModel` Function:**
- Added checks for URI existence to prevent potential errors.
- **Sequential Model Processing:**
- Changed model processing to run sequentially, replacing the previous …
> fix several issues with import files

- packages/@dcl/inspector/src/lib/babylon/decentraland/SceneContext.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/nft.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/video-player.ts
- packages/@dcl/inspector/src/lib/data-layer/host/fs-utils.ts
When dragging and dropping assets (particularly NFTs and smart items) into the canvas, there was a race condition where the asset would fail to load on the first attempt but succeed on subsequent attempts. This occurred because the asset was requested before it was fully downloaded and available in the filesystem.
Implemented a retry mechanism in the `SceneContext.getFile()` method to handle cases where an asset is temporarily unavailable. This provides a more robust solution without introducing unnecessary complexity.
Key changes:
- Added retry logic to `getFile()` with a maximum of 3 attempts
- Added 500ms delay between retries to allow for asset availability
- Improved error logging for debugging purposes
This change improves the reliability of asset loading in the Inspector, …
> fix: Load smart item asset path

- packages/@dcl/inspector/src/lib/logic/catalog.ts
This PR adds the new categories added by https://github.com/decentraland/asset-packs/pull/133
Also it will support new categories without breaking, and a catch-all "Other" category for assets without a category.
> fix: handle new categories without breaking

- packages/@dcl/inspector/src/components/EntityInspector/AnimatorInspector/AnimatorInspector.tsx
- packages/@dcl/inspector/src/components/EntityInspector/AnimatorInspector/utils.ts
closes https://github.com/decentraland/creator-hub/issues/266
> fix Animator component initialization

- Makefile
- package-lock.json
- package.json
- packages/@dcl/ecs/src/components/extended/LightSource.ts
- packages/@dcl/ecs/src/components/index.ts
- packages/@dcl/ecs/src/components/types.ts
- packages/@dcl/ecs/src/index.ts
- packages/@dcl/playground-assets/etc/playground-assets.api.md
- packages/@dcl/sdk-commands/package-lock.json
- packages/@dcl/sdk-commands/package.json
- test/ecs/components/LightSource.spec.ts
- test/snapshots/development-bundles/static-scene.test.ts.crdt
- test/snapshots/development-bundles/testing-fw.test.ts.crdt
- test/snapshots/development-bundles/two-way-crdt.test.ts.crdt
- test/snapshots/production-bundles/append-value-crdt.ts.crdt
- test/snapshots/production-bundles/billboard.ts.crdt
- test/snapshots/production-bundles/cube-deleted.ts.crdt
- test/snapshots/production-bundles/cube.ts.crdt
- test/snapshots/production-bundles/cubes.ts.crdt
- test/snapshots/production-bundles/pointer-events.ts.crdt
- test/snapshots/production-bundles/schema-components.ts.crdt
- test/snapshots/production-bundles/ui.ts.crdt
- test/snapshots/production-bundles/with-main-function.ts.crdt
Related PRs
Protocol PR: https://github.com/decentraland/protocol/pull/234
E@ PR: https://github.com/decentraland/unity-explorer/pull/3113
> feat: dynamic lights

- packages/@dcl/playground-assets/etc/playground-assets.api.md
- packages/@dcl/react-ecs/src/system.ts
- packages/@dcl/sdk-commands/src/logic/bundle.ts
This PR updates the access modifier for the class `createReactBasedUiSystem`, allowing us to instantiate the system in another library, such as `@dcl/asset-packs`.
It also passes the playerHelper object as a param to the initializer method: `initAssetPack`, allowing us to access the player data from the lib `@dcl/asset-packs`.
> feat: Make createReactBasedUiSystem public

- packages/@dcl/inspector/src/components/EntityInspector/AnimatorInspector/AnimatorInspector.tsx
- packages/@dcl/inspector/src/components/EntityInspector/AnimatorInspector/utils.ts
This PR validates the animation's weight when mapping the value.
This will ensure the animation to be executed has a valid weight between 0 and 1.
> fix: Animation weight value

- packages/@dcl/inspector/package-lock.json
- packages/@dcl/inspector/package.json
- packages/@dcl/inspector/src/components/EntityInspector/AdminToolkitView/SmartItemControl/SmartItemControl.tsx
- packages/@dcl/inspector/src/lib/sdk/operations/entitySyncUtils.spec.ts
- packages/@dcl/inspector/src/lib/sdk/operations/entitySyncUtils.ts
This PR adds the following components to be synced when being used by the AdminTools Smart Item: 
- AudioSource (if present or used by an Action)
- Animator (if present or used by an Action)
- Transform
- Tween (if present or used by an Action)
- VideoPlayer (if present or used by an Action)
- VisibilityComponent
Depends on: https://github.com/decentraland/asset-packs/pull/164
> fix: Add SyncComponents to Smart Items when using the AdminTools

- packages/@dcl/ecs/src/engine/index.ts
- packages/@dcl/ecs/src/engine/types.ts
- packages/@dcl/inspector/src/lib/data-layer/host/utils/composite-dirty.ts
- packages/@dcl/inspector/src/lib/data-layer/host/utils/engine-to-composite.ts
- packages/@dcl/playground-assets/etc/playground-assets.api.md
- packages/@dcl/sdk-commands/package-lock.json
- test/ecs/components/Name.spec.ts
- test/snapshots/development-bundles/static-scene.test.ts.crdt
- test/snapshots/development-bundles/testing-fw.test.ts.crdt
- test/snapshots/development-bundles/two-way-crdt.test.ts.crdt
- test/snapshots/production-bundles/append-value-crdt.ts.crdt
- test/snapshots/production-bundles/billboard.ts.crdt
- test/snapshots/production-bundles/cube-deleted.ts.crdt
- test/snapshots/production-bundles/cube.ts.crdt
- test/snapshots/production-bundles/cubes.ts.crdt
- test/snapshots/production-bundles/pointer-events.ts.crdt
- test/snapshots/production-bundles/schema-components.ts.crdt
- test/snapshots/production-bundles/ui.ts.crdt
- test/snapshots/production-bundles/with-main-function.ts.crdt
This PR introduces a new feature to automatically generate TypeScript definitions for entity names in the scene. It simplifies referencing scene entities by name with full type safety and IDE autocompletion support.
- Added a new function `generateEntityNamesType` to create a TypeScript file with string literal types for entity names
- Automatically generates this file whenever the scene composite is saved
- Creates both a string literal union type and a constant object for better developer experience
- Entity names are properly sanitized for valid TypeScript identifiers
- Type safety when referencing entities by name in code
- Autocomplete support in IDE for all named entities in the scene
- Prevents runtime errors from typos in entity name strings
- Makes refactoring entity names easier …
> feat: add type safe entity names file

- packages/@dcl/inspector/src/components/Renderer/Shortcuts/Shortcuts.css
- packages/@dcl/inspector/src/components/Renderer/Shortcuts/Shortcuts.tsx
Close: https://github.com/decentraland/creator-hub/issues/553
- Update rotate camera shortcut copy
- Change shortcut window width to fit the new text
> feat: change shortcut for rotating camera

- packages/@dcl/inspector/src/components/EntityInspector/AudioSourceInspector/utils.ts
- packages/@dcl/inspector/src/components/ui/FileUploadField/FileUploadField.tsx
The global property was not being saved on the audio source component. Now we are saving it but only when you select a valid audio source. If not, it does not keep the selection. This issue was already discussed with Ezio and it will be hanlded in another ticket, as it's something that it's happening in more than one component.
https://github.com/user-attachments/assets/5a991bdd-e287-43e4-b333-33ef3c467a87
> Update global value on Audio Source component

- codecov.yml
- packages/@dcl/sdk-commands/src/commands/start/explorer-alpha.ts
- packages/@dcl/sdk-commands/src/commands/start/index.ts
- test/sdk-commands/commands/start/explorer-alpha.spec.ts
This PR adds support for string-based boolean flags in the `sdk-commands start` command, specifically for explorer-alpha parameters. This allows more flexible control over boolean values and fixes issues with flag parsing.
- **String-based boolean flags**: Changed `--skip-auth-screen`, `--debug`, and `--landscape-terrain-enabled` from `Boolean` to `String` type
- **New flag**: Added `--open-deeplink-in-new-instance` (String) for controlling whether to open new explorer instances
- **String validation**: Properly handles `'true'`, `'false'`, and undefined values
```bash
sdk-commands start --explorer-alpha --skip-auth-screen=true
sdk-commands start --explorer-alpha --skip-auth-screen=false
sdk-commands start --explorer-alpha -n
```
> feat: Add string-based boolean flags for explorer-alpha parameters

- packages/@dcl/sdk-commands/src/commands/start/explorer-alpha.ts
- packages/@dcl/sdk-commands/src/commands/start/index.ts
- test/sdk-commands/commands/start/explorer-alpha.spec.ts
When running the `dcl start` command with boolean flags like `--landscape-terrain-enabled` without providing a value, the command would fail. This happened because the code was treating these parameters as strings and trying to convert them to booleans, but when no value was provided, the conversion would fail.
And the creator-hub sometimes use that flag without a value so some users where having issues to preview their scenes.
Example of the failing command:
```bash
npm start -- --explorer-alpha --landscape-terrain-enabled
```
> fix required params

- packages/@dcl/inspector/src/components/AssetPreview/AssetPreview.tsx
- packages/@dcl/inspector/src/components/AssetPreview/types.ts
- packages/@dcl/inspector/src/components/AssetPreview/utils.ts
- packages/@dcl/inspector/src/components/ImportAsset/Slider/AssetSlides.tsx
- packages/@dcl/inspector/src/components/ImportAsset/Slider/Slider.tsx
- packages/@dcl/inspector/src/components/ImportAsset/Slider/types.ts
- packages/@dcl/inspector/src/components/ImportAsset/Slider/useSliderAssets.ts
- packages/@dcl/inspector/src/components/ImportAsset/types.ts
- packages/@dcl/inspector/src/components/ImportAsset/utils.ts
- Detecting whether a GLB/GLTF file is an emote or a regular model to show the correct preview and UI behavior.
- Ensures that emotes have filenames ending with _emote. If not, the suffix is automatically appended to the name during processing.
To test:
- Import a model, check that it's uploaded correctly
- Import an emote, check that the preview is working and that it's uploaded correctly
- If the emote has the _emote at the end of the name, it will be uploaded directly. Otherwise, it will be automatically added to the emote name
> Improve import emotes 

- packages/@dcl/inspector/src/lib/babylon/decentraland/gizmo-manager.ts
- packages/@dcl/inspector/src/lib/data-layer/host/utils/engine-to-composite.ts
- packages/@dcl/sdk-commands/src/commands/start/server/file-watch-notifier.ts
- packages/@dcl/sdk-commands/src/logic/bundle.ts
- packages/@dcl/sdk-commands/src/logic/debounce.ts
- scripts/prepare.spec.ts
- avoid doing a Hot reload every time you click on the editor canvas.
EntityNames was being updated every time there was a change on the editor, and this was generating a re-build of the index.js file so we were doing unnecessary builds of the code, causing sometimes another hot-reload.
Add a mechanism of cache to check if we need to re-write the file, this way we ensure that if we do an update its really necessary.
Every time there was a change in a model, or a file that is not a code file, we were generating a re-build of the bin/index.js  file. If the build took some time it can cause another hot-reload.
Now we use a custom watch to only watch the chagnes in the .ts files.
Also add a debounce in the watcher to avoid running the re-build on every change. This was sometimes generating …
> avoid bundle of index.js if there is a change that is not a .ts file.

- packages/@dcl/inspector/src/lib/babylon/decentraland/camera.ts
- packages/@dcl/inspector/src/lib/babylon/setup/input.ts
closes https://github.com/decentraland/creator-hub/issues/682
> fix camera movement

- packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.tsx
- packages/@dcl/inspector/src/lib/babylon/decentraland/EcsEntity.ts
Reset gltfAssetContainerLoading future to ensure new animations  are loaded when switching between different GLTF models
https://github.com/user-attachments/assets/a4ac955e-2e24-4d7d-88ae-552e067c15f1
> feat: Update animations after changing GLTF

- .github/workflows/sync-main-to-experimental.yml
This PR updates the sync workflow to explicitly use a merge strategy (git pull --no-rebase) when pulling changes from main into experimental.
This prevents workflow failures caused by divergent branches and ensures consistent behavior when syncing changes.
> chore: fix sync main to experimental when branches diverge

- packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/gltf-container.ts
Update borders of entities outside the limits when changing the GLTF
Before
https://github.com/user-attachments/assets/3be4c267-9729-4176-9cde-fe3345a2cdd5
After
https://github.com/user-attachments/assets/2ae88022-9f98-4e1e-8e2c-dbdcf03c86d5
> feat: Fix issue on bounding box when updating the entity GLTF

- .github/workflows/sync-main-to-experimental.yml
Added continue-on-error instruction in YAML
> fix: sync main to experiment CI action error interruption

- packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/SceneInspector.tsx
- packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/types.ts
- packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/utils.spec.ts
- packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/utils.ts
- packages/@dcl/inspector/src/components/ui/RangeHourField/RangeHourField.css
- packages/@dcl/inspector/src/components/ui/RangeHourField/RangeHourField.tsx
- packages/@dcl/inspector/src/components/ui/RangeHourField/types.ts
- packages/@dcl/inspector/src/lib/babylon/decentraland/editorComponents/selection.ts
- packages/@dcl/inspector/src/lib/data-layer/client/feeded-local-fs.ts
- packages/@dcl/inspector/src/lib/data-layer/host/utils/component.ts
- packages/@dcl/inspector/src/lib/data-layer/host/utils/migrations/migrate-scene-metadata.ts
- packages/@dcl/inspector/src/lib/sdk/components/SceneMetadata.ts
- packages/@dcl/inspector/src/lib/sdk/components/index.ts
- packages/@dcl/sdk-commands/src/commands/start/explorer-alpha.ts
- test/sdk-commands/commands/start/explorer-alpha.spec.ts
- Add skybox config on scene settings (skybox time and trasition)
- The skybox sets the time of the scene while the transition sets how the skybox moves from the current time to the scene time
-  When the skybox value is setted, it cannot be changed from the scene itself
- Run migration to move data from SceneMetadata componente to SceneMetadata-v1 component
- Support easy versioning for future changes of properties
To test:
As it includes a migration of the scene metada componente, please test this feature in new scenes and old scenes.
https://github.com/user-attachments/assets/89400a19-5e64-47d1-bebe-f493868716ad
https://github.com/user-attachments/assets/30369b3a-67a8-4632-a0a3-020eddcb2e17
> Skybox time settings - Versioning SceneMetada component
