decentraland/js-sdk-toolchain

packages/decentraland-ecs/.gitignore, packages/decentraland-ecs/package.json, packages/decentraland-ecs/src/setupExport.ts, packages/decentraland-ecs/src/setupProxy.ts, scripts/build.spec.ts, test/decentraland-ecs/setup-export.spec.ts
Compile and add setupProxy and setupExport files in Typescript
=> feat: setupProxy and setupExport in typescript 

.github/workflows/ci.yml, packages/decentraland-ecs/package.json
Remove wip version to deploy to decentraland-ecs package. Add CLI version requirement
To start to test in the @next version.
=> chore: remove wip version to deploy to decentraland-ecs package

.github/workflows/ci.yml
Add a step to comment the installable package with an URL, also change the S3 secrets for CI.
Make PR and branches testing easier
=> chore: change s3 secrets and comment an installable package to test

packages/decentraland-ecs/package.json
Set the kernel and unity-renderer versions fixed.
...
=> fix @dcl/kernel and @dcl/unity-renderer dependencies version

packages/decentraland-ecs/package.json
https://github.com/decentraland/unity-renderer/issues/1147#issuecomment-915298273
=> chore: update renderer version

packages/decentraland-ecs/package.json
Update the kernel version with renderer-version selection, new loading gif, etc.
=> chore: update kernel version

packages/decentraland-ecs/src/setupExport.ts, test/decentraland-ecs/setup-export.spec.ts
Replace `{{ scene.scene.base }}` to sceneJson base position
https://github.com/decentraland/kernel/pull/60
https://github.com/decentraland/sdk/issues/84
=> feat: add scene base position in export.html

.github/workflows/check-versions.yml
Closes https://github.com/decentraland/sdk/issues/80
=> add github actions to verify posix version

packages/decentraland-ecs/src/setupExport.ts, test/decentraland-ecs/setup-export.spec.ts
Revert to write mappings file in the export folder
=> fix: add mappings file to export

packages/@dcl/amd/package-lock.json, packages/@dcl/amd/package.json, packages/decentraland-ecs/package.json, packages/decentraland-ecs/src/decentraland/Events.ts, packages/decentraland-ecs/types/dcl/decentraland-ecs.api.json, packages/decentraland-ecs/types/dcl/decentraland-ecs.api.md, packages/decentraland-ecs/types/dcl/index-beta.d.ts, packages/decentraland-ecs/types/dcl/index-full.d.ts, packages/decentraland-ecs/types/dcl/index.d.ts
Don't merge until https://github.com/decentraland/posix/pull/4 is merged and the posix package updated.
https://github.com/decentraland/sdk/issues/113
=> feat: add onPointerLockedStateChange event

packages/decentraland-ecs/src/decentraland/UIShapes.ts, packages/decentraland-ecs/types/dcl/decentraland-ecs.api.json, packages/decentraland-ecs/types/dcl/decentraland-ecs.api.md, packages/decentraland-ecs/types/dcl/index-beta.d.ts, packages/decentraland-ecs/types/dcl/index-full.d.ts, packages/decentraland-ecs/types/dcl/index.d.ts
fix the odd behavior where `onTextSubmit` and `onChanged` callbacks were triggered but `value` never changed accordingly
=> fix: UIInputText value update

packages/decentraland-ecs/src/decentraland/Input.ts, packages/decentraland-ecs/types/dcl/decentraland-ecs.api.json, packages/decentraland-ecs/types/dcl/decentraland-ecs.api.md, packages/decentraland-ecs/types/dcl/index-beta.d.ts, packages/decentraland-ecs/types/dcl/index-full.d.ts, packages/decentraland-ecs/types/dcl/index.d.ts
renamed action buttons:
ACTION_1 > ACTION_3
ACTION_2 > ACTION_4
ACTION_3 > ACTION_5
ACTION_4 > ACTION_6
=> refactor: rename action buttons

packages/decentraland-ecs/package.json, packages/decentraland-ecs/src/cli/setupUtils.ts, packages/decentraland-ecs/src/cli/wearables.ts
Remove the type definition in this code, and replace for @dcl/schemas ones. 
To unify the typings.
=> chore: remove ItemASsetJson type.

packages/decentraland-ecs/src/decentraland/Components.ts, packages/decentraland-ecs/src/decentraland/UIEvents.ts, packages/decentraland-ecs/src/decentraland/UIShapes.ts, packages/decentraland-ecs/src/ecs/Component.ts, packages/decentraland-ecs/types/dcl/decentraland-ecs.api.json, packages/decentraland-ecs/types/dcl/decentraland-ecs.api.md, packages/decentraland-ecs/types/dcl/index-beta.d.ts, packages/decentraland-ecs/types/dcl/index-full.d.ts, packages/decentraland-ecs/types/dcl/index.d.ts
lots of components had properties that were not used/implemented at all
=> chore: remove unused components properties

.github/workflows/ci.yml
Closes https://github.com/decentraland/sdk/issues/152
=> chore: add a test npm install in CI from s3 url

packages/@dcl/legacy-ecs/src/decentraland/Components.ts, packages/decentraland-ecs/package.json, packages/decentraland-ecs/types/dcl/decentraland-ecs.api.json, packages/decentraland-ecs/types/dcl/decentraland-ecs.api.md, packages/decentraland-ecs/types/dcl/index-beta.d.ts, packages/decentraland-ecs/types/dcl/index-full.d.ts, packages/decentraland-ecs/types/dcl/index.d.ts
Add the component AvatarTexture.
Unity Renderer PR:
- https://github.com/decentraland/unity-renderer/pull/1773
https://github.com/decentraland/sdk/issues/64
=> feat: add the component AvatarTexture

packages/decentraland-ecs/src/setupProxy.ts
Add a feature-flag endpoint which fetches the .zone feature flags.
https://github.com/decentraland/sdk/issues/179
=> feat: add feature flag endpoint

packages/@dcl/js-runtime/index.d.ts, packages/decentraland-ecs/package.json, packages/decentraland-ecs/types/env/index.d.ts
Counterpart of https://github.com/decentraland/kernel/pull/228
=> chore: unify requestinit

packages/@dcl/ecs/test/components/CameraModeArea.spec.ts, packages/@dcl/ecs/tools/protocol-buffer-generation/index.ts, packages/@dcl/sdk/types/ecs7/index.d.ts
This readd the camera mode area component to the ECS 7
=> feat: re-add  camera mode area component

packages/@dcl/ecs/package-lock.json, packages/@dcl/ecs/package.json, packages/@dcl/ecs/test/components/CameraMode.spec.ts, packages/@dcl/ecs/test/components/CameraModeArea.spec.ts, packages/@dcl/ecs/test/components/PointerLock.spec.ts, packages/@dcl/sdk/types/ecs7/index.d.ts
As stated in the following doc https://github.com/decentraland/sdk/blob/main/docs/static-entities.md
we are adding CameraMode and PointerLock components for CameraEntity that are going to be sent from the renderer
=> feat: `CameraMode` & `PointerLock` components

packages/decentraland-ecs/package.json, packages/decentraland-ecs/src/cli/mock-catalyst/index.ts, packages/decentraland-ecs/src/setupProxy.ts
added `post` endpoint `/content/entities/active`
=> fix: preview scenes fetch

packages/@dcl/ecs/package-lock.json, packages/@dcl/ecs/package.json, packages/@dcl/ecs/src/systems/crdt/index.ts, packages/@dcl/ecs/src/systems/crdt/utils.ts
Move the CRDT key from a string to a pair of numbers
=> chore: bump @dcl/crdt

packages/@dcl/ecs/etc/ecs.api.md, packages/@dcl/ecs/package-lock.json, packages/@dcl/ecs/package.json, packages/@dcl/ecs/test/components/Material.spec.ts, packages/@dcl/ecs/test/components/MeshRenderer.spec.ts, packages/@dcl/ecs/test/components/UiText.spec.ts, packages/@dcl/sdk/types/ecs7/index.d.ts
related to issue: https://github.com/decentraland/sdk/issues/366
adds `MeshRenderer` ecs component
=> feat: MeshRenderer ECS component

packages/@dcl/ecs/package-lock.json, packages/@dcl/ecs/package.json, packages/@dcl/ecs/src/index.ts, packages/@dcl/react-ecs/etc/react-ecs.api.md, packages/@dcl/react-ecs/package-lock.json, packages/@dcl/react-ecs/src/components/index.tsx, packages/@dcl/react-ecs/src/components/types.ts, packages/@dcl/react-ecs/src/components/uiText/types.ts, packages/@dcl/react-ecs/src/react-ecs.ts, packages/@dcl/react-ecs/src/reconciler/index.ts, packages/@dcl/sdk/types/ecs7/index.d.ts, scripts/build.spec.ts, test/ecs/components/UiText.spec.ts, test/ecs/react-ui/text.spec.tsx
Add UiText to react-ecs.
```ts
import { UIEntity, ReactEcs } from '@dcl/react-ecs'
const ui = () => (
<UiEntity uiTransform={{ width: 100 }} uiText={{ value: 'Some Text', color: { r: 1, g: 1, b: 1 } }} />
)
```
=> add ui text

packages/@dcl/ecs/etc/ecs.api.md, packages/@dcl/ecs/package-lock.json, packages/@dcl/ecs/package.json, packages/@dcl/react-ecs/etc/react-ecs.api.md, packages/@dcl/react-ecs/package-lock.json, packages/@dcl/react-ecs/src/components/index.tsx, packages/@dcl/react-ecs/src/components/types.ts, packages/@dcl/react-ecs/src/components/uiStyles/types.ts, packages/@dcl/react-ecs/src/react-ecs.ts, packages/@dcl/react-ecs/src/reconciler/index.ts, packages/@dcl/sdk/types/ecs7/index.d.ts, scripts/build.spec.ts, test/ecs/components/AvatarShape.spec.ts, test/ecs/react-ui/styles.spec.tsx
depends on https://github.com/decentraland/protocol/pull/50
Add `UiStyles` component for the UI.
We want to split the style component from the layout.
i.e.
```ts
<UiEntity uiTransform={{ width: 10 }} uiStyles={{ backgroundColor: { r: 1, g: 1, b: 2, a: 1 } } />
```
=> add uiStyles component

packages/@dcl/ecs/package-lock.json, packages/@dcl/ecs/package.json
My bad, I merged https://github.com/decentraland/js-sdk-toolchain/pull/263 without changing @dcl/protocol. 
Wrong button 💀
=> fix @dcl/protocol

packages/@dcl/ecs/etc/ecs.api.md, packages/@dcl/ecs/src/engine/index.ts, packages/@dcl/ecs/src/engine/types.ts, packages/@dcl/react-ecs/package-lock.json, packages/@dcl/sdk/types/ecs7/index.d.ts
Add the reference to Player and Camera entities.
https://github.com/decentraland/sdk/issues/456
=> chore: add special entities ref

test/ecs/snippets/cube-spawner/index.ts, test/ecs/snippets/pointer-events/index.ts
removed `BoxShape` from `cube-spawner`
added `MeshCollider` to `pointer-events`
=> chore: update snippets

.github/workflows/ci.yml, Makefile, packages/@dcl/ecs/package-lock.json, packages/@dcl/ecs/package.json, packages/@dcl/ecs/src/components/index.ts, packages/@dcl/ecs/src/engine/events.ts, packages/@dcl/ecs/src/runtime/initialization.ts, packages/@dcl/react-ecs/package-lock.json, packages/@dcl/react-ecs/src/components/uiStyles/types.ts, packages/@dcl/react-ecs/src/components/uiText/types.ts, packages/@dcl/react-ecs/src/components/uiTransform/types.ts, scripts/build.spec.ts, scripts/protocol-buffer-generation/componentSchemaTemplate.ts, scripts/protocol-buffer-generation/generateProtocolBuffer.ts, scripts/protocol-buffer-generation/generateProtocolTypes.ts, scripts/protocol-buffer-generation/index.ts, scripts/rpc-api-generation/index.ts, test/ecs/components/AvatarModifierArea.spec.ts, test/ecs/components/CameraMode.spec.ts, test/ecs/components/CameraModeArea.spec.ts, test/ecs/components/Material.spec.ts, test/ecs/components/MeshCollider.spec.ts, test/ecs/components/OnPointerDown.spec.ts, test/ecs/components/PointerEvents.spec.ts, test/ecs/components/PointerEventsResult.spec.ts, test/ecs/components/Raycast.spec.ts, test/ecs/components/UiComponent.spec.ts, test/ecs/events/isPointerEventActive.spec.ts, test/ecs/events/wasEntityClicked.spec.ts
New approach required by https://github.com/decentraland/protocol/pull/57
=> chore: change protocol-buffer root path

packages/@dcl/react-ecs/package-lock.json, packages/@dcl/react-ecs/src/reconciler/index.ts
fix reconcielr for NaN values.
=> fix ui playground reconciler

packages/@dcl/dcl-rollup/ecs.config.ts, packages/@dcl/dcl-rollup/libs.config.ts, packages/@dcl/react-ecs/api-extractor.json, packages/@dcl/react-ecs/etc/react-ecs.api.md, packages/@dcl/react-ecs/src/components/index.tsx, packages/@dcl/react-ecs/src/components/listeners/types.ts, packages/@dcl/react-ecs/src/components/types.ts, packages/@dcl/react-ecs/src/react-ecs.ts, packages/@dcl/react-ecs/src/reconciler/index.ts, packages/@dcl/react-ecs/src/reconciler/types.ts, packages/@dcl/react-ecs/src/reconciler/utils.ts, packages/@dcl/react-ecs/src/system.ts, scripts/helpers.ts, test/ecs/components/MeshCollider.spec.ts, test/ecs/events/utils.ts, test/ecs/events/wasEntityClicked.spec.ts, test/ecs/events/wasJustClicked.spec.ts, test/ecs/react-ui/listeners.spec.tsx
- Fail the build if there are some tsc errors.
- Add onClick events for the UI
```tsx
function handleClick() {
// Do something onClick
}
const ui = () => (
<UiEntity uiTransform={{ width: 100 }} onClick={handleClick} />
)
renderUi(ui)
```
TODO:
=> Pointer Events for UI

packages/@dcl/ecs/etc/ecs.api.md, packages/@dcl/ecs/src/engine/entity.ts, packages/@dcl/ecs/src/engine/index.ts, packages/@dcl/ecs/src/engine/input.ts, packages/@dcl/ecs/src/engine/types.ts, packages/@dcl/ecs/src/runtime/initialization/index.ts, packages/@dcl/ecs/src/systems/events.ts, packages/@dcl/sdk/types/ecs7/index.d.ts, test/build-ecs/fixtures/ecs7-scene/game.ts, test/ecs/entity.spec.ts, test/ecs/events/system.spec.ts, test/ecs/events/utils.ts
Add EventsSystem callbacks =>  `onPointerDown`, `onPointerUp` & `onClick`
Remove EventsSystem callbacks => `removeOnPointerDown`, `removeOnPointerUp` & `removeOnClick`
Add callback style for onClick & onPointerDown fns to be more readable.
```ts
EventsSystem.onPointerDown(
entity,
function () {
createCube(1 + Math.random() * 8, Math.random() * 8, 1 + Math.random() * 8)
EventsSystem.removeOnPointerDown(entity)
},
{
button: InputAction.IA_PRIMARY,
hoverText: 'CASLA - BOEDO'
}
)
EventsSystem.onClick(entity, fn, { button, hoverText })
EventsSystem.onPointerDown(entity, fn)
EventsSystem.onPointerUp(entity, fn)
EventsSystem.removeOnPointerUp(entity)
EventsSystem.removeOnPointerDown(entity)
EventsSystem.removeOnPointerUp(entity)
```
=>  EventsSystem manager for Pointers

packages/@dcl/ecs/src/engine/entity-utils.ts, packages/@dcl/ecs/src/engine/entity.ts, packages/@dcl/ecs/src/engine/index.ts, packages/@dcl/ecs/src/engine/types.ts, packages/@dcl/playground-assets/etc/playground-assets.api.md, test/ecs/crdt.spec.ts, test/ecs/entity.spec.ts, test/ecs/monsterdb.spec.tsx, test/ecs/transports.spec.ts
=> Fix entities limit

packages/@dcl/playground-assets/package-lock.json, packages/@dcl/sdk/package.json
Dependency: release CLI 3.14.1
=> chore: bump unity-renderer and minCliVersion

packages/@dcl/ecs/package-lock.json, packages/@dcl/ecs/package.json, packages/@dcl/playground-assets/etc/playground-assets.api.md, packages/@dcl/react-ecs/package-lock.json, test/build-ecs/fixtures/ecs7-ui/src/ui.tsx, test/ecs/components/TextShape.spec.ts, test/react-ecs/text.spec.tsx
closes https://github.com/decentraland/sdk/issues/473
=> remove deprecated font

.github/workflows/ci.yml, Makefile, packages/@dcl/crdt/.gitignore, packages/@dcl/crdt/README.md, packages/@dcl/crdt/package-lock.json, packages/@dcl/crdt/package.json, packages/@dcl/crdt/src/index.ts, packages/@dcl/crdt/src/types.ts, packages/@dcl/crdt/tsconfig.json, packages/@dcl/ecs/package-lock.json, packages/@dcl/ecs/package.json, packages/@dcl/react-ecs/package-lock.json, scripts/build.spec.ts, scripts/common.ts, scripts/prepare.spec.ts, test/crdt/arraybuffer.spec.ts, test/crdt/crdt.spec.ts, test/crdt/data.spec.ts, test/crdt/data/arraybuffer.test, test/crdt/data/crdt.test, test/crdt/data/shuffle.test, test/crdt/processMessage.spec.ts, test/crdt/shuffle.spec.ts, test/crdt/utils/index.ts, test/crdt/utils/sandbox.ts, test/crdt/utils/snapshot.ts, test/crdt/utils/state.ts
- migrates CRDT to this monorepo
- separates pipeline in [test, lint, build]
- adds codecov to report coverage on each build
=> migrate crdt repo to toolchain monorepo

packages/@dcl/ecs/package-lock.json, packages/@dcl/ecs/package.json, packages/@dcl/playground-assets/etc/playground-assets.api.md, packages/@dcl/playground-assets/package-lock.json, packages/@dcl/react-ecs/package-lock.json, packages/@dcl/sdk/package.json
Part of https://github.com/decentraland/sdk/issues/527
=> chore: update protocol, add new restricted actions

packages/@dcl/dcl-rollup/index.ts
fixes https://github.com/decentraland/sdk/issues/523
=> fix: exitCode=1 on failed compilation

packages/@dcl/playground-assets/etc/playground-assets.api.md, packages/@dcl/react-ecs/src/components/types.ts
```tsx
[1,2,3,4].map((index) => <Label key={index} value={`Index: ${index}`} />)
```
=> add key type for custom components

.vscode/settings.json, packages/@dcl/sdk/src/index.ts, packages/@dcl/sdk/src/message-bus.ts, packages/@dcl/sdk/src/observables.ts, test/__mocks__/~system/EngineApi.js, test/ecs/runtime.spec.ts, test/snapshots/append-value-crdt.ts.crdt, test/snapshots/billboard.ts.crdt, test/snapshots/cube-deleted.ts.crdt, test/snapshots/cube.ts.crdt, test/snapshots/cubes.ts.crdt, test/snapshots/helpers/ui.tsx, test/snapshots/pointer-events.ts.crdt, test/snapshots/schema-components.ts.crdt, test/snapshots/two-way-crdt.ts.crdt, test/snapshots/ui.ts.crdt
Fix message bus & onCommsMessage observable.
Closes https://github.com/decentraland/sdk/issues/572
=> Fix MessageBus

packages/@dcl/inspector/src/components/tree/Tree.css, packages/@dcl/inspector/src/components/tree/Tree.tsx, packages/@dcl/inspector/src/index.css, packages/@dcl/inspector/src/index.tsx
=> chore: lint

packages/@dcl/sdk-commands/package.json, packages/@dcl/sdk-commands/src/components/analytics.ts, test/sdk-commands/utils/analytics.spec.ts
remove the src folder when packing the sdk-commnads pacakage
=> add packageversion for analytics old dashboards

packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk-commands/package.json, packages/@dcl/sdk-commands/src/commands/build/index.ts, packages/@dcl/sdk-commands/src/commands/deploy/index.ts, packages/@dcl/sdk-commands/src/commands/deploy/linker-dapp/api.ts, packages/@dcl/sdk-commands/src/commands/deploy/linker-dapp/catalyst-pointers.ts, packages/@dcl/sdk-commands/src/commands/deploy/linker-dapp/routes.ts, packages/@dcl/sdk-commands/src/commands/export-static/index.ts, packages/@dcl/sdk-commands/src/commands/start/index.ts, packages/@dcl/sdk-commands/src/logic/account.ts, packages/@dcl/sdk-commands/src/logic/dcl-info.ts, packages/@dcl/sdk-commands/src/logic/get-free-port.ts, packages/@dcl/sdk-commands/src/logic/project-files.ts, packages/@dcl/sdk-commands/src/logic/project-validations.ts, packages/@dcl/sdk-commands/src/logic/scene-validations.ts, scripts/build.spec.ts, test/sdk-commands/commands/build/helpers.spec.ts, test/sdk-commands/commands/build/index.spec.ts, test/sdk-commands/utils/scene-validation.spec.ts
Same deploy command we already had in CLI but with a refactored Linker API
=> Add 'deploy' command

packages/@dcl/sdk-commands/src/commands/build/index.ts, packages/@dcl/sdk-commands/src/commands/deploy/index.ts, packages/@dcl/sdk-commands/src/components/analytics.ts
As required in https://github.com/decentraland/sdk/issues/529
=> Add tracking analytics to 'deploy' command

packages/@dcl/ecs/package-lock.json, packages/@dcl/ecs/package.json, packages/@dcl/inspector/package-lock.json, packages/@dcl/playground-assets/etc/playground-assets.api.md, packages/@dcl/react-ecs/package-lock.json, packages/@dcl/react-ecs/src/components/Input/index.tsx, test/ecs/components/UiInput.spec.ts, test/snapshots/append-value-crdt.ts.crdt, test/snapshots/billboard.ts.crdt, test/snapshots/cubes.ts.crdt, test/snapshots/pointer-events.ts.crdt, test/snapshots/ui.ts.crdt
Related PRs:
* https://github.com/decentraland/protocol/pull/118
* https://github.com/decentraland/unity-renderer/pull/4582
=> chore: ui input text value property

packages/@dcl/ecs/src/systems/crdt/utils.ts, test/ecs/crdt-rules-lww.spec.ts, test/snapshots/append-value-crdt.ts.crdt, test/snapshots/billboard.ts.crdt, test/snapshots/cube-deleted.ts.crdt, test/snapshots/cube.ts.crdt, test/snapshots/cubes.ts.crdt, test/snapshots/pointer-events.ts.crdt, test/snapshots/schema-components.ts.crdt, test/snapshots/two-way-crdt.ts.crdt, test/snapshots/ui.ts.crdt
First, compare the length, and decide from that what the greater is. Then the previous lexicographical comparison.
Improvement of performance, although is a rare case, for now, the definition of this data comparison should be one from the beginning of the runtime.
=> feat: change dataCompare to first length comparison and then lexicographical

packages/decentraland-ecs/package.json
=> (sdk6) chore: upgrade explorer package

package-lock.json, package.json, packages/@dcl/ecs/src/composite/serialization.ts, packages/@dcl/inspector/src/components/Renderer/Renderer.tsx, packages/@dcl/inspector/src/hooks/sdk/useRenderer.ts, packages/@dcl/inspector/src/hooks/sdk/useSdkContext.ts, packages/@dcl/inspector/src/index.tsx, packages/@dcl/inspector/src/lib/data-layer/client/feededLocalFs.ts, packages/@dcl/inspector/src/lib/data-layer/client/local-data-layer.ts, packages/@dcl/inspector/src/lib/data-layer/host/engine-to-composite.ts, packages/@dcl/inspector/src/lib/data-layer/host/engine.ts, packages/@dcl/inspector/src/lib/data-layer/host/fs-composite-provider.ts, packages/@dcl/inspector/src/lib/data-layer/host/index.ts, packages/@dcl/inspector/src/lib/data-layer/host/rpc-methods.ts, packages/@dcl/inspector/src/lib/data-layer/host/stream.ts, packages/@dcl/inspector/src/lib/data-layer/remote-data-layer.ts, packages/@dcl/inspector/src/lib/data-layer/types.ts, packages/@dcl/inspector/src/lib/logic/in-memory-storage.ts, packages/@dcl/inspector/src/lib/sdk/engine.ts, packages/@dcl/playground-assets/etc/playground-assets.api.md, packages/@dcl/sdk-commands/src/commands/start/data-layer/fs.ts, packages/@dcl/sdk-commands/src/commands/start/data-layer/rpc.ts, packages/@dcl/sdk-commands/src/commands/start/data-layer/ws.ts, packages/@dcl/sdk-commands/src/commands/start/index.ts, packages/@dcl/sdk-commands/src/commands/start/server/routes.ts, test/ecs/composite.spec.ts
Add `sdk-commands` integration of file system interface based on Node.js FileSystem API
=> feat: integrate file system to data-layer

packages/@dcl/react-ecs/src/reconciler/index.ts, packages/@dcl/sdk/package.json, test/react-ecs/leak.spec.tsx, test/snapshots/package-lock.json, test/snapshots/production-bundles/ui.ts.crdt
revert temp fix for ui pointer events not working.
proper fix was added on renderer side https://github.com/decentraland/unity-renderer/pull/4857
closes https://github.com/decentraland/sdk/issues/632
=> revert: fix pointer events partially ([#456](https://github.com/decentraland/js-sdk-toolchain/pull/456))

packages/@dcl/inspector/public/index.html, packages/@dcl/inspector/src/lib/data-layer/client/index.ts
Editor part: https://github.com/decentraland/editor-sdk7/pull/20
Closes https://github.com/decentraland/sdk/issues/696
=> feat: add reading data-layer ws from globalthis

packages/@dcl/sdk-commands/src/commands/init/index.ts, packages/@dcl/sdk-commands/src/commands/init/repos.ts, packages/@dcl/sdk-commands/src/logic/fs.ts, test/sdk-commands/commands/init/index.spec.ts, test/sdk-commands/utils/fs.spec.ts
- Add --project param to choose between `scene` and `editor`
- Add back from previous CLI the param --template (internal)
With editor PR closes https://github.com/decentraland/sdk/issues/749
=> chore: add editor repo to init command

scripts/rpc-api-generation/index.ts
`import { spawn, kill } from '~system/PortableExperience`
=> expose portable expereience service

packages/@dcl/playground-assets/etc/playground-assets.api.md, packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk/src/message-bus.ts, packages/@dcl/sdk/src/observables.ts, test/snapshots/package-lock.json
closes https://github.com/decentraland/sdk/issues/728
=> fix: message bus not sending changes to self

packages/@dcl/inspector/src/lib/data-layer/client/feeded-local-fs.ts
closes https://github.com/decentraland/sdk/issues/776
=> fix: wrong hardcoded composite

packages/@dcl/inspector/src/components/Toolbar/Gizmos/Gizmos.tsx
This slipped through in my last PR 🙏
=> fix: panel should not be always open

packages/@dcl/sdk-commands/src/logic/beautiful-logs.ts, packages/@dcl/sdk-commands/src/logic/bundle.ts, packages/@dcl/sdk-commands/src/logic/composite.ts
=> chore: prettier composite errors

package-lock.json, package.json, packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk-commands/package.json
* Updated protocol to have `TeleportTo` restricted action
Issue: https://github.com/decentraland/sdk/issues/768
Related PRs:
* https://github.com/decentraland/protocol/pull/150
* https://github.com/decentraland/unity-renderer/pull/5192
* https://github.com/decentraland/scene-runtime/pull/195
=> chore: update teleportation restricted actions

packages/@dcl/inspector/src/lib/sdk/components.ts
=> fix: EntityNode name

packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk-commands/src/commands/start/index.ts, packages/@dcl/sdk-commands/src/logic/project-validations.ts, test/sdk-commands/utils/validations.spec.ts
Context: https://github.com/decentraland/js-sdk-toolchain/pull/622#issuecomment-1572781025
Closes https://github.com/decentraland/sdk/issues/567
Closes https://github.com/decentraland/js-sdk-toolchain/pull/622
=> fix auto-import ~system for vscode [Approach 2]

packages/@dcl/inspector/src/components/ProjectAssetExplorer/ProjectView.tsx
closes https://github.com/decentraland/sdk/issues/820
=> fix: project view nested deep multi-file

packages/@dcl/inspector/src/lib/babylon/decentraland/gizmo-manager.ts, packages/@dcl/inspector/src/lib/babylon/decentraland/layout-manager.ts, packages/@dcl/inspector/src/lib/data-layer/client/feeded-local-fs.ts
=> fix: grid only visible after changing parcels

packages/@dcl/inspector/src/components/ProjectAssetExplorer/ProjectAssetExplorer.css
closes https://github.com/decentraland/sdk/issues/847
=> fix: folder view tiles height styles

packages/@dcl/inspector/src/lib/data-layer/host/scene.ts, packages/@dcl/inspector/src/lib/data-layer/host/utils/fs-composite-provider.ts, packages/@dcl/inspector/src/lib/data-layer/types.ts, packages/@dcl/inspector/src/lib/logic/in-memory-storage.ts, packages/@dcl/sdk-commands/src/commands/start/data-layer/fs.ts
closes https://github.com/decentraland/sdk/issues/851
=> fix: main composite to lower case

packages/@dcl/inspector/src/components/ImportAsset/ImportAsset.tsx, packages/@dcl/inspector/src/components/Renderer/Renderer.tsx, packages/@dcl/inspector/src/lib/data-layer/host/rpc-methods.ts
closes https://github.com/decentraland/sdk/issues/849
=> fix: dirs & naming when importing files

packages/@dcl/inspector/src/lib/data-layer/host/fs-utils.ts, packages/@dcl/inspector/src/lib/data-layer/host/rpc-methods.ts, packages/@dcl/inspector/src/lib/data-layer/host/scene.ts
closes https://github.com/decentraland/sdk/issues/864
=> update: scene path

packages/@dcl/inspector/src/components/Assets/Assets.tsx, packages/@dcl/inspector/src/components/AssetsCatalog/AssetsCatalog.tsx, packages/@dcl/inspector/src/components/AssetsCatalog/types.ts, packages/@dcl/inspector/src/components/Loading/Loading.tsx, packages/@dcl/inspector/src/components/Loading/index.ts, packages/@dcl/inspector/src/components/Loading/types.ts, packages/@dcl/inspector/src/components/Renderer/Renderer.tsx, packages/@dcl/inspector/src/hooks/catalog/useCatalog.spec.ts, packages/@dcl/inspector/src/hooks/catalog/useCatalog.ts, packages/@dcl/inspector/src/lib/data-layer/host/fs-utils.ts
closes https://github.com/decentraland/sdk/issues/863
=> fix: assets loading blocking UI

packages/@dcl/ecs/src/engine/index.ts, packages/@dcl/ecs/src/engine/types.ts, packages/@dcl/ecs/src/runtime/helpers/tree.ts, packages/@dcl/playground-assets/etc/playground-assets.api.md, packages/@dcl/sdk/package.json, test/ecs/engine.spec.ts
Update renderer to the latest version
=> add remove entity with children to the engine

package-lock.json, package.json, packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk-commands/package.json, test/snapshots/package-lock.json
=> chore: bump `@dcl/protocol` to add `TriggerSceneEmote` restricted action

packages/@dcl/sdk-commands/src/commands/start/index.ts
context: https://github.com/decentraland/unity-renderer/issues/5497
=> restore old backpack on preview

packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json
Upgrade `@dcl/mini-rpc` to `v1.0.7`
=> fix: upgrade @dcl/mini-rpc to v1.0.7

packages/@dcl/inspector/src/components/AssetsCatalog/AssetsCatalog.tsx, packages/@dcl/inspector/src/components/AssetsCatalog/index.ts, packages/@dcl/inspector/src/components/AssetsCatalog/types.ts, packages/@dcl/inspector/src/components/AssetsCatalog/utils.ts, packages/@dcl/inspector/src/components/Renderer/Renderer.tsx, packages/@dcl/inspector/src/hooks/catalog/useCatalog.spec.ts, packages/@dcl/inspector/src/hooks/catalog/useCatalog.ts, packages/@dcl/inspector/src/lib/data-layer/client/builder-utils.ts, packages/@dcl/inspector/src/lib/data-layer/client/feeded-local-fs.ts, packages/@dcl/inspector/src/lib/sdk/context.ts, packages/@dcl/inspector/src/lib/sdk/drag-drop.ts, packages/@dcl/inspector/src/lib/sdk/test-local-scene/index.ts
This PR replaces the use of the builder server with the new [builder items CDN](https://github.com/decentraland/asset-packs).
=> feat: use static cnd instead of builder server

packages/@dcl/inspector/src/lib/logic/config.ts
Otherwise this breaks on VSCode
=> fix: use globalThis instead of window

packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json, packages/@dcl/inspector/src/components/AssetsCatalog/types.ts, packages/@dcl/inspector/src/components/AssetsCatalog/utils.ts, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerInspector.tsx, packages/@dcl/inspector/src/components/Hierarchy/ContextMenu/ContextMenu.tsx, packages/@dcl/inspector/src/components/ProjectAssetExplorer/types.ts, packages/@dcl/inspector/src/components/Renderer/Renderer.tsx, packages/@dcl/inspector/src/hooks/catalog/useCatalog.spec.ts, packages/@dcl/inspector/src/hooks/catalog/useCatalog.ts, packages/@dcl/inspector/src/lib/data-layer/client/builder-utils.ts, packages/@dcl/inspector/src/lib/logic/config.ts, packages/@dcl/inspector/src/lib/sdk/operations/add-asset.ts, packages/@dcl/inspector/src/lib/sdk/operations/add-child.ts, packages/@dcl/inspector/src/lib/sdk/tree.spec.ts
This PR adds the logic to detect the components of the asset and insert the UI components in the inspector.
=> feat: Drag and Drop smart items

packages/@dcl/inspector/src/components/Assets/Assets.tsx, packages/@dcl/inspector/src/lib/logic/catalog.ts
Prevent smart items from showing in the catalog when they are disabled
=> feat: prevent smart items from showing in the catalog when they are disabled

README.md, packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.tsx, packages/@dcl/inspector/src/components/Hierarchy/ContextMenu/ContextMenu.tsx, packages/@dcl/inspector/src/index.tsx, packages/@dcl/inspector/src/lib/data-layer/host/utils/composite-dirty.ts, packages/@dcl/inspector/src/lib/sdk/components/index.ts
This PR integrates the new `ActionTypes` component.
=> feat: action types

packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerInspector.css
=> fix: styles in TriggerComponent

packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/CounterInspector/CounterInspector.css, packages/@dcl/inspector/src/components/EntityInspector/CounterInspector/CounterInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/CounterInspector/index.ts, packages/@dcl/inspector/src/components/EntityInspector/CounterInspector/types.ts, packages/@dcl/inspector/src/components/EntityInspector/CounterInspector/utils.ts, packages/@dcl/inspector/src/components/EntityInspector/EntityInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/StatesInspector/StatesInspector.css, packages/@dcl/inspector/src/components/EntityInspector/StatesInspector/StatesInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerAction/TriggerAction.tsx, packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerAction/types.ts, packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerCondition/TriggerCondition.tsx, packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerCondition/types.ts, packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerEvent/TriggerEvent.tsx, packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerEvent/types.ts, packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerInspector.tsx, packages/@dcl/inspector/src/components/Hierarchy/ContextMenu/ContextMenu.tsx, packages/@dcl/inspector/src/lib/data-layer/host/utils/composite-dirty.ts, packages/@dcl/inspector/src/lib/sdk/components/index.ts, packages/@dcl/inspector/src/lib/sdk/operations/add-child.ts, packages/@dcl/inspector/src/lib/sdk/operations/add-component.ts
Use our own ids instead of relying on entity ids which could change between loads of the composite
=> feat: remove entity ids

packages/@dcl/inspector/src/components/AssetsCatalog/AssetsCatalog.css, packages/@dcl/inspector/src/components/AssetsCatalog/AssetsCatalog.tsx, packages/@dcl/inspector/src/vars.css
This PR adds the smart item asset badge and background color.
=> feat: Add smart-item asset badge

packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json, packages/@dcl/sdk-commands/package-lock.json
=> feat: upgrade @dcl/asset-packs

packages/@dcl/inspector/src/components/ImportAsset/utils.ts, packages/@dcl/inspector/src/components/Renderer/Renderer.tsx, packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/gltf-container.ts
Fixes https://github.com/decentraland/sdk/issues/946
=> fix: delete item after refresh

packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json, packages/@dcl/inspector/src/lib/sdk/operations/add-asset.ts, packages/@dcl/inspector/src/lib/sdk/operations/add-component.ts, packages/@dcl/inspector/src/lib/sdk/operations/duplicate-entity.ts
Fixes https://github.com/decentraland/sdk/issues/953
=> fix: remap component ids and triggers when doing a duplicate entity

packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.tsx, packages/@dcl/inspector/src/lib/babylon/decentraland/EcsEntity.ts, packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/gltf-container.ts
This PR fixes the loading asset animations in the ActionComponent.
Closes https://github.com/decentraland/sdk/issues/947
=> fix: Asset loading animations in ActionComponent

packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json, packages/@dcl/inspector/src/components/Assets/Assets.tsx, packages/@dcl/inspector/src/components/AssetsCatalog/AssetsCatalog.tsx, packages/@dcl/inspector/src/lib/logic/catalog.ts
Adds new categories for smart items and adds tooltip to show asset names
=> feat: smart item categories and tooltip

packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerEvent/TriggerEvent.tsx
This PR fixes the trigger event dropdown text
=> fix: Trigger event dropdown texts

packages/@dcl/inspector/src/components/Renderer/Renderer.tsx, packages/@dcl/sdk-commands/package-lock.json
This fixes the inspector being laggy
=> fix: get rid of lag

packages/@dcl/inspector/src/lib/logic/analytics.ts
This PR adds the appId on each event property. 
This change avoids joining multiple tables in segment to link the events.
=> feat: Send appId in the properties

packages/@dcl/inspector/src/components/Container/Container.css, packages/@dcl/inspector/src/components/Container/Container.tsx, packages/@dcl/inspector/src/components/Container/types.ts, packages/@dcl/inspector/src/components/EntityInspector/EntityInspector.css
This PR updates the container component styles, defining a better margin between components.
Closes: https://github.com/decentraland/sdk/issues/983
=> feat: Update Inspector Container component

packages/@dcl/inspector/src/components/EntityInspector/GltfInspector/GltfInspector.tsx, packages/@dcl/inspector/src/components/ui/FileUploadField/FileUploadField.css, packages/@dcl/inspector/src/components/ui/FileUploadField/FileUploadField.tsx, packages/@dcl/inspector/src/components/ui/FileUploadField/index.ts, packages/@dcl/inspector/src/components/ui/FileUploadField/types.ts, packages/@dcl/inspector/src/components/ui/TextField/TextField.css, packages/@dcl/inspector/src/components/ui/index.ts
This is a wrapper for the TextField component, allowing drag and drop files from the Assets component.
Closes https://github.com/decentraland/sdk/issues/980
=> feat: Add FileUploadField

packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlaySoundAction/PlaySoundAction.css, packages/@dcl/inspector/src/components/ui/RangeField/RangeField.css, packages/@dcl/inspector/src/components/ui/RangeField/RangeField.tsx
This PR fixes the Range Field styles.
=> fix: Range Field styles

packages/@dcl/inspector/src/components/App/App.tsx, packages/@dcl/inspector/src/components/Container/Container.css, packages/@dcl/inspector/src/components/Container/Container.tsx, packages/@dcl/inspector/src/components/Container/types.ts, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/AudioSourceInspector/AudioSourceInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/CounterInspector/CounterInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/EntityInspector.css, packages/@dcl/inspector/src/components/EntityInspector/GltfInspector/GltfInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/MaterialInspector/MaterialInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/MeshColliderInspector/MeshColliderInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/MeshRendererInspector/MeshRendererInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/MoreOptionsMenu/MoreOptionsMenu.tsx, packages/@dcl/inspector/src/components/EntityInspector/StatesInspector/StatesInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/TextShapeInspector/TextShapeInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/TransformInspector/TransformInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/VisibilityComponentInspector/VisibilityComponentInspector.tsx, packages/@dcl/inspector/src/components/ui/Dropdown/Dropdown.css, packages/@dcl/inspector/src/components/ui/Dropdown/Dropdown.tsx
This PR fixes some style issues for the inspector components.
- Update LeftPanel default and min size
- Update RightPanel default and min size
- Increase the font size for the selected  entity name in the RightPanel
- Increase the font size for the component name in the RightPanel
- Adds a contextual menu for the components in the RightPanel
=> fix: Inspector component styles

packages/@dcl/sdk/package.json
=> feat: upgrade renderer

packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.css, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/TweenAction/TweenAction.tsx
closes https://github.com/decentraland/smart-items/issues/36
=> fix: tween range field to allow decimals

packages/@dcl/inspector/src/components/EntityInspector/MeshColliderInspector/MeshColliderInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/MeshRendererInspector/MeshRendererInspector.tsx
This PR updates the Mesh Renderer/Collider Inspector component styles and uses the new UI components.
=> feat: Update Mesh Renderer/Collider Inspector Components

packages/@dcl/inspector/src/components/Block/Block.css, packages/@dcl/inspector/src/components/Block/Block.tsx, packages/@dcl/inspector/src/components/EntityInspector/MeshColliderInspector/MeshColliderInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/MeshRendererInspector/MeshRendererInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/TextShapeInspector/TextShapeInspector.tsx, packages/@dcl/inspector/src/components/ui/HybridField/HybridField.css
This PR updates the Text Shape Inspector component styles and uses the new UI components.
=> feat: Update Text Shape Inspector Component

packages/@dcl/inspector/src/components/Block/Block.css, packages/@dcl/inspector/src/components/Block/Block.tsx, packages/@dcl/inspector/src/components/Container/Container.css, packages/@dcl/inspector/src/components/Container/Container.tsx, packages/@dcl/inspector/src/components/Container/types.ts, packages/@dcl/inspector/src/components/EntityInspector/MaterialInspector/MaterialInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/MaterialInspector/Texture/Texture.tsx, packages/@dcl/inspector/src/components/EntityInspector/MaterialInspector/Texture/utils.ts, packages/@dcl/inspector/src/components/EntityInspector/MeshColliderInspector/MeshColliderInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/MeshRendererInspector/MeshRendererInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/TextShapeInspector/TextShapeInspector.tsx, packages/@dcl/inspector/src/components/ui/CheckboxField/CheckboxField.css, packages/@dcl/inspector/src/components/ui/CheckboxField/CheckboxField.tsx, packages/@dcl/inspector/src/components/ui/ColorField/ColorField.css, packages/@dcl/inspector/src/components/ui/ColorField/ColorField.tsx, packages/@dcl/inspector/src/components/ui/FileUploadField/FileUploadField.tsx, packages/@dcl/inspector/src/components/ui/HybridField/HybridField.css, packages/@dcl/inspector/src/components/ui/HybridField/HybridField.tsx, packages/@dcl/inspector/src/components/ui/RangeField/RangeField.css, packages/@dcl/inspector/src/components/ui/RangeField/RangeField.tsx
This PR updates the Material Inspector component styles and uses the new UI components.
=> feat: Update Material Inspector Component

packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/SetVisibilityAction/SetVisibilityAction.tsx, packages/@dcl/inspector/src/components/Renderer/Renderer.tsx, packages/@dcl/inspector/src/lib/logic/analytics.ts, packages/@dcl/inspector/src/lib/logic/catalog.ts, packages/@dcl/inspector/src/lib/logic/config.ts, packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk-commands/package.json
This PR updates the inspector tracking events, adding the property: `isSmart` when adding a new item to the scene and the property `projectId` to all the events, allowing track scenes easily
=> feat: Update inspector tracking events

packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/MovePlayerAction/MovePlayerAction.css, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/MovePlayerAction/MovePlayerAction.tsx, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/MovePlayerAction/index.ts, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/MovePlayerAction/types.ts, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/OpenLinkAction/OpenLinkAction.css, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/OpenLinkAction/OpenLinkAction.tsx, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/OpenLinkAction/index.ts, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/OpenLinkAction/types.ts, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlayCustomEmoteAction/PlayCustomEmoteAction.css, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlayCustomEmoteAction/PlayCustomEmoteAction.tsx, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlayCustomEmoteAction/index.ts, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlayCustomEmoteAction/types.ts, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlayCustomEmoteAction/utils.ts, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlayDefaultEmoteAction/PlayDefaultEmoteAction.css, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlayDefaultEmoteAction/PlayDefaultEmoteAction.tsx, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlayDefaultEmoteAction/index.ts, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlayDefaultEmoteAction/types.ts, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/TeleportPlayerAction/TeleportPlayerAction.css, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/TeleportPlayerAction/TeleportPlayerAction.tsx, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/TeleportPlayerAction/index.ts, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/TeleportPlayerAction/types.ts, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/utils.ts
This PR integrates the following actions:
- Teleport Player
- Move Player
- Play Default Emote
- Play Custom Emote
- Open Link
The Move Player and Play Custom Emote actions are disabled because they have bugs that need to be fixed in the SDK before we can enable them.
=> feat: added new actions

packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ShowImageAction/ShowImageAction.css, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ShowImageAction/ShowImageAction.tsx, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ShowImageAction/index.ts, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ShowImageAction/types.ts, packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerEvent/TriggerEvent.tsx, packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerInspector.tsx, packages/@dcl/inspector/src/components/ui/Message/Message.css, packages/@dcl/inspector/src/components/ui/RangeField/RangeField.tsx, packages/@dcl/inspector/src/components/ui/RangeField/types.ts
This PR adds the Show Image Action container component
depends on: https://github.com/decentraland/asset-packs/pull/80
=> feat: Show image action

packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json, packages/@dcl/sdk-commands/package-lock.json
This PR upgrades the @dcl/asset-packs package
=> chore: Upgrade @dcl/asset-packs package

packages/@dcl/inspector/src/components/ProjectAssetExplorer/Tile/Tile.css, packages/@dcl/inspector/src/components/ProjectAssetExplorer/Tile/Tile.tsx, packages/@dcl/inspector/src/lib/data-layer/host/fs-utils.ts, packages/@dcl/inspector/src/lib/data-layer/host/undo-redo.ts, packages/@dcl/inspector/src/redux/data-layer/index.ts, packages/@dcl/inspector/src/redux/data-layer/sagas/connect.spec.ts, packages/@dcl/inspector/src/redux/data-layer/sagas/index.ts, packages/@dcl/inspector/src/redux/data-layer/sagas/remove-asset.ts
This PR adds the missing remove asset event.
https://github.com/decentraland/js-sdk-toolchain/assets/3170051/d2e6538c-afc9-4859-9c0d-153eda6989d8
=> fix: Remove Assets

packages/@dcl/sdk/package.json
=> feat: upgrade @dcl/explorer

packages/@dcl/inspector/src/components/AssetsCatalog/AssetsCatalog.tsx, packages/@dcl/inspector/src/components/AssetsCatalog/Header/Header.tsx, packages/@dcl/inspector/src/components/AssetsCatalog/Header/types.ts, packages/@dcl/inspector/src/components/AssetsCatalog/Themes/Themes.tsx, packages/@dcl/inspector/src/lib/logic/analytics.ts
This PR improves the asset catalog search logic and tracks the items found.
=> feat: Improve search logic and track items found

packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/SceneInspector.tsx
Remove tags field and limit categories to max of 3
=> fix: remove tags and limit categories to 3

packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json
=> fix: upgrade @dcl/asset-packs

packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json, packages/@dcl/sdk-commands/package-lock.json
This PR upgrades the `@dcl/asset-packs` package
=> feat: Upgrade @dcl/asset-packs package

packages/@dcl/inspector/src/components/Renderer/Metrics/Metrics.tsx, packages/@dcl/inspector/src/lib/babylon/decentraland/EcsEntity.ts, packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/gltf-container.ts, packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/mesh-renderer.ts, packages/@dcl/inspector/src/lib/babylon/setup/setup.ts
This PR addresses two issues.
1) The incorrect detection of the mesh bounding box when loading assets from the catalog
2) Fixes the misplaced bounding box position
=> fix: BoundingBox mesh detection

packages/@dcl/dcl-rollup/ecs.config.ts, packages/@dcl/dcl-rollup/libs.config.ts, packages/@dcl/dcl-rollup/package-lock.json, packages/@dcl/dcl-rollup/package.json, packages/@dcl/dcl-rollup/tsconfig.json, packages/@dcl/legacy-ecs/package-lock.json, packages/@dcl/legacy-ecs/package.json, packages/@dcl/legacy-ecs/src/decentraland/Components.ts, packages/@dcl/legacy-ecs/src/ecs/Component.ts, packages/@dcl/legacy-ecs/src/ecs/Engine.ts, packages/@dcl/legacy-ecs/src/ecs/Observable.ts, packages/@dcl/legacy-ecs/src/ecs/helpers.ts, packages/@dcl/legacy-ecs/tsconfig.json, packages/decentraland-ecs/types/dcl/decentraland-ecs.api.json, packages/decentraland-ecs/types/dcl/decentraland-ecs.api.md, packages/decentraland-ecs/types/dcl/index-beta.d.ts, packages/decentraland-ecs/types/dcl/index-full.d.ts, packages/decentraland-ecs/types/dcl/index.d.ts, scripts/build.spec.ts, scripts/common.ts, scripts/prepare.spec.ts
Reverts decentraland/js-sdk-toolchain#886
=> Revert "fix: Update legacy-ecs package"

Makefile, package-lock.json, package.json, packages/@dcl/ecs/src/components/extended/AudioSource.ts, packages/@dcl/ecs/src/components/index.ts, packages/@dcl/ecs/src/components/types.ts, packages/@dcl/ecs/src/index.ts, packages/@dcl/playground-assets/etc/playground-assets.api.md, packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk-commands/package.json, test/ecs/components/AudioSource.spec.ts
Add `playSound/stopSound` helpers for AudioSource component
=> add playSound/stopSound AudioSource methods

packages/@dcl/inspector/src/components/ImportAsset/ImportAsset.tsx, packages/@dcl/sdk-commands/package-lock.json
Fixes https://github.com/decentraland/sdk/issues/1098
=> fix: ignore some error codes on gltf validation

package-lock.json, package.json, packages/@dcl/ecs/src/components/extended/AudioStream.ts, packages/@dcl/ecs/src/components/index.ts, packages/@dcl/ecs/src/components/types.ts, packages/@dcl/ecs/src/index.ts, packages/@dcl/playground-assets/etc/playground-assets.api.md, packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk-commands/package.json, scripts/protocol-buffer-generation/generateIndex.ts, test/ecs/components/AudioEvent.spec.ts, test/ecs/components/AudioStream.spec.ts
[ShapeUp Cycle 6](https://www.notion.so/decentraland/AudioStream-connection-enhancement-fc8e4e7840c446ad89c53bcc60c1050f)
=> add AudioEvent component

packages/@dcl/inspector/src/components/EntityInspector/TransformInspector/TransformInspector.tsx
Closes https://github.com/decentraland/sdk/issues/1102
=> feat: reorder transform fields

packages/@dcl/inspector/src/components/EntityInspector/SmartItemBasicView/TweenView/TweenView.tsx, packages/@dcl/inspector/src/components/Renderer/Renderer.tsx
Fixes: https://github.com/decentraland/sdk/issues/1108
=> fix: Operation reference

packages/@dcl/sdk/package.json
Upgrade `@dcl/explorer` to the latest version
=> chore: upgrade explorer

packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/TriggerProximityAction/TriggerProximityAction.tsx, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/TriggerProximityAction/types.ts, packages/@dcl/inspector/src/components/EntityInspector/SmartItemBasicView/ActionView/ActionView.tsx, packages/@dcl/inspector/src/components/EntityInspector/SmartItemBasicView/ActionView/index.ts, packages/@dcl/inspector/src/components/EntityInspector/SmartItemBasicView/CounterBarView/CounterBarView.tsx, packages/@dcl/inspector/src/components/EntityInspector/SmartItemBasicView/CounterBarView/index.ts, packages/@dcl/inspector/src/components/EntityInspector/SmartItemBasicView/SmartItemBasicView.tsx, packages/@dcl/inspector/src/components/Hierarchy/Hierarchy.tsx, packages/@dcl/inspector/src/components/ui/Dropdown/utils.ts, packages/@dcl/inspector/src/lib/sdk/components/index.ts, packages/@dcl/inspector/src/lib/utils/strings.ts, packages/@dcl/sdk-commands/package-lock.json
This PR adds two new smart items basic view components to interact with `Actions` and `Counters`.
=> feat: Game smart items simplified view

package-lock.json, package.json, packages/@dcl/playground-assets/etc/playground-assets.api.md, packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk-commands/package.json
Updated protocol to enable new avatar attach points.
=> feat: add more avatar attach points

packages/@dcl/inspector/src/components/Box/Box.tsx, packages/@dcl/inspector/src/components/Button/Button.css, packages/@dcl/inspector/src/components/Button/types.ts, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/Grid/Grid.css, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/Grid/Grid.tsx, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/Grid/index.ts, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/Grid/types.ts, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/Grid/utils.spec.ts, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/Grid/utils.ts, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/Layout.css, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/Layout.tsx, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/ModeAdvanced/Advanced.tsx, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/ModeAdvanced/ModeAdvanced.tsx, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/ModeAdvanced/index.ts, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/ModeAdvanced/types.ts, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/index.ts, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/types.ts, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/utils.spec.ts, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/Layout/utils.ts, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/SceneInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/types.ts, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/utils.spec.ts, packages/@dcl/inspector/src/components/EntityInspector/SceneInspector/utils.ts, packages/@dcl/inspector/src/lib/data-layer/client/feeded-local-fs.ts
Add new scene parcels editor
[Figma](https://www.figma.com/file/sXjsoASo7nc24UY6OZnR1d/%F0%9F%A7%B0-Editor-bug-fixes-%7C-Builder-%7C-Cycle-6?type=design&node-id=1502-21056&mode=design&t=JnomtHgeIzQ5w02W-4) (ask ezio for permissions)
=> Add new Scene Layout

packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlayVideoStreamAction/PlayVideoStreamAction.tsx, packages/@dcl/inspector/src/components/EntityInspector/PointerEventsInspector/utils.ts, packages/@dcl/inspector/src/components/EntityInspector/SmartItemBasicView/VideoView/VideoView.tsx, packages/@dcl/sdk-commands/package-lock.json
Closes: https://github.com/decentraland/smart-items/issues/39
Closes: https://github.com/decentraland/smart-items/issues/43
=> fix: Smart items details

packages/@dcl/sdk/package.json
This reverts commit b701277939f21021c5b0cfe33e85cb4c56f4d797.
=> Revert "chore: bump `@dcl/explorer` (#968)"

packages/@dcl/sdk/package.json
=> feat: upgrade explorer release 20240702

package-lock.json, package.json, packages/@dcl/playground-assets/etc/playground-assets.api.md, packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk-commands/package.json, scripts/prepare.spec.ts
=> chore: mark aapt_position as depcreated

packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk-commands/package.json, packages/@dcl/sdk-commands/src/commands/deploy/index.ts, packages/@dcl/sdk-commands/src/commands/deploy/utils.ts, packages/@dcl/sdk-commands/src/commands/quests/utils.ts, packages/@dcl/sdk-commands/src/linker-dapp/routes.ts
This PR updates the auth flow behavior and uses the `AuthChain` object obtained from the `linker-dapp`.
Depends on: https://github.com/decentraland/linker-dapp/pull/37
=> feat: Update auth flow

packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk-commands/package.json, packages/@dcl/sdk-commands/src/linker-dapp/routes.ts, test/snapshots/package-lock.json
This PR fixes the linker-dapp /auth handler.
=> fix: Linker dapp handler

package-lock.json, package.json, packages/@dcl/playground-assets/etc/playground-assets.api.md, packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk-commands/package.json, test/ecs/components/VirtualCamera.spec.ts
Updated protocol and adapted to it.
Related PRs:
* https://github.com/decentraland/protocol/pull/219
* https://github.com/decentraland/unity-explorer/pull/2058
* https://github.com/decentraland/sdk7-test-scenes/pull/17
=> chore: virtual camera components iteration

packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.tsx
closes https://github.com/decentraland/sdk/issues/1118
=> fix Actions deletion

packages/@dcl/inspector/src/components/EntityInspector/GltfInspector/utils.ts
closes https://github.com/decentraland/sdk/issues/1104
=> add physics and pointer option for collision layers

packages/@dcl/inspector/src/components/EntityInspector/TextShapeInspector/utils.ts
closes https://github.com/decentraland/sdk/issues/1132
=> allow TextShape outline width decimals

packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json, packages/@dcl/inspector/src/components/App/App.tsx, packages/@dcl/inspector/src/components/Assets/Assets.css, packages/@dcl/inspector/src/components/Assets/Assets.tsx
This PR fixes the min size assets panel size.
https://github.com/user-attachments/assets/1f851e1f-dda1-4902-93d0-7b54b288092a
=> fix: Panels size

packages/@dcl/inspector/README.md
=> chore: update readme

packages/@dcl/inspector/src/components/EntityInspector/SmartItemBasicView/ActionView/ActionView.tsx
This PR adds the TextArea field as a supported component for the BasicView Actions
=> feat: Update BasicView Actions to handle TextArea fields

packages/@dcl/inspector/src/components/AssetsCatalog/Categories/Categories.css, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/ActionInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/AudioSourceInspector/AudioSourceInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/AudioSourceInspector/types.ts, packages/@dcl/inspector/src/components/EntityInspector/MaterialInspector/MaterialInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/TriggerInspector/TriggerInspector.tsx, packages/@dcl/inspector/src/components/Renderer/Shortcuts/Shortcuts.tsx, packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/material.ts
closes https://github.com/decentraland/creator-hub/issues/415
closes https://github.com/decentraland/creator-hub/issues/255
closes https://github.com/decentraland/creator-hub/issues/261
closes https://github.com/decentraland/creator-hub/issues/418
closes https://github.com/decentraland/creator-hub/issues/256
=> fix several issues

package-lock.json, package.json, packages/@dcl/playground-assets/etc/playground-assets.api.md, packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk-commands/package.json
Related PRs:
* https://github.com/decentraland/protocol/pull/248 ([test version](https://github.com/decentraland/protocol/pull/245))
* https://github.com/decentraland/unity-explorer/pull/3328
=> feat: avatarTarget param addition in movePlayerTo()

package-lock.json, package.json, packages/@dcl/playground-assets/etc/playground-assets.api.md, packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk-commands/package.json, test/ecs/components/VirtualCamera.spec.ts, test/snapshots/development-bundles/static-scene.test.ts.crdt, test/snapshots/development-bundles/testing-fw.test.ts.crdt, test/snapshots/development-bundles/two-way-crdt.test.ts.crdt, test/snapshots/package-lock.json, test/snapshots/production-bundles/append-value-crdt.ts.crdt, test/snapshots/production-bundles/billboard.ts.crdt, test/snapshots/production-bundles/cube-deleted.ts.crdt, test/snapshots/production-bundles/cube.ts.crdt, test/snapshots/production-bundles/cubes.ts.crdt, test/snapshots/production-bundles/pointer-events.ts.crdt, test/snapshots/production-bundles/schema-components.ts.crdt, test/snapshots/production-bundles/ui.ts.crdt, test/snapshots/production-bundles/with-main-function.ts.crdt
Updating the experimental protocol package used to enable using the new `fov` field for SDK's `VirtualCamera` component.
Related PRs:
* https://github.com/decentraland/protocol/pull/250
* https://github.com/decentraland/unity-explorer/pull/3487
=> feat: virtual camera fov

packages/@dcl/inspector/src/lib/babylon/decentraland/camera.spec.ts, packages/@dcl/inspector/src/lib/babylon/decentraland/camera.ts, packages/@dcl/inspector/src/lib/babylon/decentraland/gizmo-manager.ts, packages/@dcl/inspector/src/lib/babylon/decentraland/mouse-utils.ts
close https://github.com/decentraland/creator-hub/issues/325
=> update left/right click button behaviour on renderer

packages/@dcl/inspector/src/components/EntityInspector/SmartItemBasicView/AdminToolsBasicView/AdminToolsBasicView.tsx, packages/@dcl/inspector/src/lib/data-layer/host/utils/composite-dirty.ts, packages/@dcl/inspector/src/lib/data-layer/host/utils/migrations/select-scene-entity.ts
closes https://github.com/decentraland/creator-hub/issues/320
=> select "Scene" in tree on startup

packages/@dcl/inspector/src/components/Assets/Assets.css, packages/@dcl/inspector/src/components/Assets/Assets.tsx, packages/@dcl/inspector/src/components/ProjectAssetExplorer/ProjectAssetExplorer.tsx
closes https://github.com/decentraland/creator-hub/issues/406
=> add refresh button for Assets

packages/@dcl/inspector/src/components/Renderer/Renderer.tsx, packages/@dcl/inspector/src/lib/babylon/decentraland/editorComponents/selection.ts, packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/gltf-container.ts
closes https://github.com/decentraland/creator-hub/issues/383
=> add entity highlight when selected

packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/material.ts
closes https://github.com/decentraland/creator-hub/issues/356
=> fix: Texture being flipped vertically

package-lock.json, package.json, packages/@dcl/inspector/package-lock.json, packages/@dcl/inspector/package.json, packages/@dcl/inspector/src/components/EntityInspector/ActionInspector/PlaySoundAction/PlaySoundAction.tsx, packages/@dcl/inspector/src/components/EntityInspector/AdminToolkitView/VideoControl/VideoControl.css, packages/@dcl/inspector/src/components/EntityInspector/SmartItemBasicView/VideoScreenBasicView/VideoScreenBasicView.css, packages/@dcl/sdk-commands/package-lock.json
Support global property on play sound when adding an action.
Depends on: https://github.com/decentraland/asset-packs/pull/172/files
https://github.com/user-attachments/assets/cfdcc281-55ad-4bdf-8c90-8339b6aa8182
=> Support global prop on play sound action

package-lock.json, package.json, packages/@dcl/sdk-commands/package-lock.json, packages/@dcl/sdk-commands/package.json
Fixed protocol pointers and lint-fix pass
=> chore: lint fix

packages/@dcl/inspector/src/lib/sdk/operations/add-asset/index.ts
Init entities collisions:
- visible layer: "none" 
- invisible layer: "cursor and pointer"
https://github.com/user-attachments/assets/aa40d7fa-c96e-444e-bff2-bcb8a7ff9f67
=> Init GLTF componente wiht invisible layer phisics and pointer

packages/@dcl/inspector/src/components/EntityInspector/MaterialInspector/Texture/Texture.tsx, packages/@dcl/inspector/src/components/EntityInspector/MaterialInspector/Texture/types.ts, packages/@dcl/inspector/src/components/EntityInspector/MaterialInspector/Texture/utils.spec.ts, packages/@dcl/inspector/src/components/EntityInspector/MaterialInspector/Texture/utils.ts, packages/@dcl/inspector/src/components/EntityInspector/MaterialInspector/utils.spec.ts, packages/@dcl/inspector/src/lib/babylon/decentraland/editorComponents/selection.ts, packages/@dcl/inspector/src/lib/babylon/decentraland/sdkComponents/material.ts
closes https://github.com/decentraland/creator-hub/issues/302
=> feat: add offset & tiling to Texture component

packages/@dcl/inspector/src/components/EntityInspector/MaterialInspector/MaterialInspector.tsx, packages/@dcl/inspector/src/components/EntityInspector/MaterialInspector/utils.ts
closes https://github.com/decentraland/creator-hub/issues/492
=> fix alphaTexture for unlit Material

packages/@dcl/inspector/src/components/EntityInspector/EntityHeader/EntityHeader.tsx
Remove add component from Scene, Camera and Player.
https://github.com/user-attachments/assets/52f154b3-02c6-4424-b2e5-a4c365c59eaa
=> feat: remove add component icon on scene, camera and player
